import { assertPublicAssetContract, type DigitalAsset } from "./contract";

/**
 * Retrato editorial inicial. Não é seed de banco e não prova propriedade.
 * Cada linha carrega a procedência que permite distinguir fato, observação e
 * declaração do dono.
 */
export const INITIAL_ASSETS: DigitalAsset[] = [
  {
    schemaVersion: 1,
    id: "asset:facebook-page:monetized-acquired",
    name: "Página monetizada adquirida",
    cluster: "social_presence",
    kind: "facebook_page",
    platform: "Meta",
    state: "declared",
    criticality: "high",
    summary: "Página comprada para a operação orgânica e de vídeo, ainda sem identidade técnica e propriedade conferidas no VOLC.",
    owner: { displayName: "Tarcisio", custody: "declared" },
    external: {},
    capabilities: ["Publicação orgânica", "Distribuição de vídeo", "Monetização declarada"],
    credential: {
      required: true,
      provider: null,
      state: "not_registered",
      note: "Escolher o cofre externo e verificar acesso com MFA antes de ativar.",
    },
    verification: { state: "unverified" },
    evidence: [
      {
        id: "ev:owner:facebook-page",
        kind: "owner_declaration",
        statement: "O dono declarou a compra de uma página de Facebook monetizada há mais de um mês.",
        observedAt: "2026-08-26",
        sourceLabel: "Relato do dono",
      },
    ],
    relations: [
      { kind: "produces_for", targetId: "cap:organic-content", targetLabel: "Operação de conteúdo orgânico", state: "declared" },
      { kind: "depends_on", targetId: "asset:service:chatpion", targetLabel: "ChatPion próprio", state: "declared" },
    ],
    nextAction: "Conferir ID da página, Business Portfolio, propriedade, monetização, administradores e método de recuperação.",
    tags: ["primeiro lote", "meta", "orgânico"],
  },
  {
    schemaVersion: 1,
    id: "asset:service:chatpion",
    name: "ChatPion próprio",
    cluster: "communities",
    kind: "messaging_hub",
    platform: "ChatPion",
    state: "restricted",
    criticality: "high",
    summary: "Superfície self-hosted publicada; páginas conectadas, permissões, fluxos e entregabilidade ainda não foram verificados.",
    owner: { displayName: "VOLC", custody: "declared" },
    external: { publicUrl: "https://chatpion.agenciavolc.com.br/" },
    capabilities: ["Automação de conversa", "Messenger", "Retenção"],
    credential: {
      required: true,
      provider: null,
      state: "not_registered",
      note: "A referência administrativa ainda não foi cadastrada em cofre especializado.",
    },
    verification: { state: "partial", checkedAt: "2026-08-26" },
    evidence: [
      {
        id: "ev:http:chatpion",
        kind: "live_observation",
        statement: "O endpoint público respondeu HTTP 200; isso prova superfície publicada, não operação configurada.",
        observedAt: "2026-08-26",
        sourceLabel: "Verificação HTTP somente leitura",
      },
    ],
    relations: [
      { kind: "depends_on", targetId: "concept:facebook-page-monetized", targetLabel: "Página monetizada adquirida", state: "declared" },
      { kind: "produces_for", targetId: "cap:owned-audience", targetLabel: "Audiência própria e retenção", state: "declared" },
    ],
    nextAction: "Inventariar versão, administradores, páginas conectadas, canais, webhooks e política de backup sem copiar credenciais.",
    tags: ["retenção", "self-hosted", "verificação parcial"],
  },
  {
    schemaVersion: 1,
    id: "asset:google-ads:credito-up",
    name: "Crédito Up",
    cluster: "paid_media",
    kind: "google_ads_account",
    platform: "Google Ads",
    state: "active",
    criticality: "critical",
    summary: "Conta operacional lida pelo Hub de Tráfego, com duas campanhas Search ENABLED observadas.",
    owner: { displayName: "VOLC", custody: "verified" },
    project: "Crédito Up",
    vertical: "Financeiro",
    external: { displayId: "•••-•••-1692" },
    capabilities: ["Search", "Leitura da conta", "Validação de campanha"],
    credential: {
      required: false,
      provider: null,
      state: "not_required",
      note: "O acesso é herdado da integração Google Ads/MCC, registrada como ativo separado na próxima etapa.",
    },
    verification: { state: "verified", checkedAt: "2026-08-27", checkedBy: "Sincronizador do Hub" },
    evidence: [
      {
        id: "ev:gads:credito-up",
        kind: "live_observation",
        statement: "A conta respondeu à sincronização real, somente leitura, com cinco campanhas no inventário.",
        observedAt: "2026-08-27",
        sourceLabel: "Google Ads API via Hub de Tráfego",
      },
    ],
    relations: [
      { kind: "managed_by", targetId: "asset:google-ads:mcc", targetLabel: "MCC Google Ads VOLC", state: "declared" },
      { kind: "spends_from", targetId: "project:credito-up", targetLabel: "Projeto Crédito Up", state: "verified" },
    ],
    nextAction: "Confirmar o vínculo das duas campanhas ativas com suas intenções internas no Hub.",
    tags: ["aquisição", "google", "financeiro"],
  },
  {
    schemaVersion: 1,
    id: "asset:google-ads:pmundo",
    name: "PMUNDO+",
    cluster: "paid_media",
    kind: "google_ads_account",
    platform: "Google Ads",
    state: "verified",
    criticality: "high",
    summary: "Conta observada pelo inventário real; o histórico domina o volume e permanece separado da operação corrente.",
    owner: { displayName: "VOLC", custody: "verified" },
    project: "PMUNDO+",
    external: { displayId: "•••-•••-8045" },
    capabilities: ["Search", "Leitura da conta"],
    credential: { required: false, provider: null, state: "not_required", note: "Acesso herdado da integração Google Ads/MCC." },
    verification: { state: "verified", checkedAt: "2026-08-27", checkedBy: "Sincronizador do Hub" },
    evidence: [
      {
        id: "ev:gads:pmundo",
        kind: "live_observation",
        statement: "A conta respondeu à sincronização real, somente leitura, com 74 campanhas no inventário.",
        observedAt: "2026-08-27",
        sourceLabel: "Google Ads API via Hub de Tráfego",
      },
    ],
    relations: [{ kind: "managed_by", targetId: "asset:google-ads:mcc", targetLabel: "MCC Google Ads VOLC", state: "declared" }],
    nextAction: "Confirmar projeto responsável, status operacional e política de retenção do histórico.",
    tags: ["aquisição", "google"],
  },
  {
    schemaVersion: 1,
    id: "asset:google-ads:portal-mundo-mais",
    name: "Portal Mundo Mais",
    cluster: "paid_media",
    kind: "google_ads_account",
    platform: "Google Ads",
    state: "verified",
    criticality: "high",
    summary: "Conta observada pelo inventário real do Hub, sem afirmar propriedade além da evidência disponível.",
    owner: { displayName: "VOLC", custody: "declared" },
    project: "Portal Mundo Mais",
    external: { displayId: "•••-•••-6539" },
    capabilities: ["Search", "Leitura da conta"],
    credential: { required: false, provider: null, state: "not_required", note: "Acesso herdado da integração Google Ads/MCC." },
    verification: { state: "verified", checkedAt: "2026-08-27", checkedBy: "Sincronizador do Hub" },
    evidence: [
      {
        id: "ev:gads:portal",
        kind: "live_observation",
        statement: "A conta respondeu à sincronização real, somente leitura, com cinco campanhas no inventário.",
        observedAt: "2026-08-27",
        sourceLabel: "Google Ads API via Hub de Tráfego",
      },
    ],
    relations: [{ kind: "managed_by", targetId: "asset:google-ads:mcc", targetLabel: "MCC Google Ads VOLC", state: "declared" }],
    nextAction: "Verificar custódia, projeto, domínio relacionado e papel atual na operação.",
    tags: ["aquisição", "google"],
  },
  {
    schemaVersion: 1,
    id: "asset:engine:image-volc",
    name: "Motor de Imagem VOLC / PRENSA",
    cluster: "creative_production",
    kind: "creative_engine",
    platform: "VOLC Factory",
    state: "verified",
    criticality: "high",
    summary: "Engine de composição determinística e geração assistida, inventariado por contrato e snapshots reproduzíveis.",
    owner: { displayName: "VOLC", custody: "verified" },
    external: {},
    capabilities: ["Tipografia real", "Layouts responsivos", "Imagem generativa", "Composição em camadas"],
    credential: { required: false, provider: null, state: "not_required", note: "Credenciais de provedores são integrações separadas, nunca atributo público deste engine." },
    verification: { state: "verified", checkedAt: "2026-08-26", checkedBy: "Inventário de Creative Engines" },
    evidence: [
      {
        id: "ev:repo:image-volc",
        kind: "repository_inventory",
        statement: "O pacote vivo registra fontes, contratos, skins, specs e renders classificados com hashes.",
        observedAt: "2026-08-26",
        sourceLabel: "docs/creative-engines",
      },
    ],
    relations: [{ kind: "produces_for", targetId: "cap:organic-content", targetLabel: "Operação de conteúdo orgânico", state: "verified" }],
    nextAction: "Registrar endpoint/adaptador interno quando a integração runtime começar.",
    tags: ["imagem", "creative engine", "PRENSA"],
  },
  {
    schemaVersion: 1,
    id: "asset:engine:video-volc",
    name: "Motor de Vídeo VOLC",
    cluster: "creative_production",
    kind: "creative_engine",
    platform: "VOLC Factory",
    state: "verified",
    criticality: "high",
    summary: "Fábrica contratual de vídeo observada fora do runtime do VOLC O.S., com formatos, skins, vozes e QA catalogados.",
    owner: { displayName: "VOLC", custody: "verified" },
    external: {},
    capabilities: ["Vídeo vertical", "Narração", "Motion", "QA técnico"],
    credential: { required: false, provider: null, state: "not_required", note: "Provedores e vozes terão ativos de integração próprios." },
    verification: { state: "verified", checkedAt: "2026-08-26", checkedBy: "Inventário de Creative Engines" },
    evidence: [
      {
        id: "ev:repo:video-volc",
        kind: "repository_inventory",
        statement: "O inventário registrou formatos, skins, nichos, vozes, MP4s e níveis de QA sem afirmar integração runtime.",
        observedAt: "2026-08-26",
        sourceLabel: "docs/creative-engines",
      },
    ],
    relations: [{ kind: "produces_for", targetId: "cap:organic-content", targetLabel: "Operação de conteúdo orgânico", state: "verified" }],
    nextAction: "Definir adaptador, fila de jobs, armazenamento e recibo antes de plugar no VOLC O.S.",
    tags: ["vídeo", "creative engine", "factory"],
  },
  {
    schemaVersion: 1,
    id: "asset:database:volc-os",
    name: "Supabase oficial VOLC O.S.",
    cluster: "infrastructure",
    kind: "database_service",
    platform: "Supabase self-hosted",
    state: "active",
    criticality: "critical",
    summary: "Única autoridade operacional de dados do projeto, self-hosted e protegida por decisão arquitetural explícita.",
    owner: { displayName: "VOLC", custody: "verified" },
    external: { publicUrl: "https://database.agenciavolc.com.br/" },
    capabilities: ["Postgres", "Auth", "PostgREST", "Storage", "Edge runtime"],
    credential: {
      required: true,
      provider: null,
      state: "review_due",
      note: "Credenciais existem fora do repositório; rotação e hardening continuam como gate pré-lançamento.",
    },
    verification: { state: "verified", checkedAt: "2026-08-27", checkedBy: "Gate de autoridade Supabase" },
    evidence: [
      {
        id: "ev:adr:supabase",
        kind: "provider_record",
        statement: "A autoridade única foi aceita, documentada e protegida por gate de inicialização.",
        observedAt: "2026-08-27",
        sourceLabel: "ADR-SUPABASE-AUTORIDADE-OPERACIONAL.md",
      },
    ],
    relations: [{ kind: "belongs_to", targetId: "system:volc-os", targetLabel: "VOLC O.S.", state: "verified" }],
    nextAction: "Executar a rotação e o hardening do runbook antes do lançamento externo.",
    tags: ["dados", "autoridade", "self-hosted"],
  },
];

assertPublicAssetContract(INITIAL_ASSETS);
