import React from 'react';
import { createRoot } from 'react-dom/client';
import { MemoryRouter } from 'react-router-dom';
import './src/index.css';
import { MetaCampaignReadView } from './src/components/trafego/meta/MetaCampaignReadView';
import { MetaCampaignDemoContext } from './src/components/trafego/meta/MetaCampaignData';
import { criarDadosDemoCampanha, CONTA_DEMO_META } from './src/components/trafego/meta/demoCampaignData';
import { FaixaDeDemonstracao } from './src/components/campaign/MetaDemoStatus';
const id='campanha-descoberta-01';
createRoot(document.getElementById('root')!).render(<MemoryRouter><main className="mx-auto max-w-7xl"><FaixaDeDemonstracao oQue="QA isolado da mesma tela demonstrativa."/><MetaCampaignDemoContext.Provider value={criarDadosDemoCampanha(id)!}><MetaCampaignReadView referencia={id} contaRef={CONTA_DEMO_META}/></MetaCampaignDemoContext.Provider></main></MemoryRouter>);
