"""Itens do checklist de fechamento de 07/10/2026, na ordem do sprint.

Cada item: (id, faixa, título curto, o que falta, concluído quando, dependência).
O status NÃO mora aqui: o gerador lê do ROADMAP-VIVO.json, para o checklist
nunca divergir da fonte que o QG mostra.
"""

FAIXAS = {
    1: "Bloqueios de integração, segurança e deploy",
    2: "Capacidades que liberam receita e operação",
    3: "Integrações incompletas",
    4: "Qualidade e confiabilidade",
    5: "Acabamento e menor impacto",
}

ITENS = [
    # ── 1. Bloqueios de integração, segurança e deploy ─────────────────────
    ("P01-T12", 1, "Levar a branch consolidada ao main",
     "Revisar a branch integration/qg-real-20261007 e mover o main para ela. Hoje o main local é a linha anterior à v2 e não tem nada de 29/08 em diante.",
     "main aponta para a branch revisada, o worktree principal continua com o trabalho dele e o push foi autorizado.",
     ""),
    ("P02-T05", 1, "Fechar grants e trocar credenciais antes de lançar",
     "Reemitir as credenciais que a auditoria marcou e aplicar REVOKE e RLS nas seis tabelas operacionais.",
     "Um teste anônimo prova zero escrita nas seis tabelas e as credenciais antigas não autenticam mais.",
     ""),
    ("P09-T03", 1, "Fechar a porta única de escrita",
     "As superfícies do n8n que ainda mudam campanha fora de /subir precisam passar pela porta ou ser desligadas.",
     "Nenhum mutate acontece fora de /subir, incluindo n8n e CLI, e há teste que falha se um caminho novo aparecer.",
     ""),
    ("P09-T17", 1, "Fechar caminhos de criação fora de /subir",
     "Faltam n8n, interface do Google Ads e campanhas antigas da conta. Também falta decidir se a implementação Hermes (c689cdb) entra, complementa ou sai.",
     "Todo produtor de campanha está listado e cada um passa pela mesma política ou foi desligado.",
     "P09-T03"),
    ("P09-T15", 1, "Gravar o primeiro recibo live do destino pago",
     "O portão roda no plano, na LP e na publicação, mas nenhum recibo live foi gravado no Supabase oficial.",
     "Uma LP publicada tem recibo live aprovado no Supabase oficial, ligado ao hash do artefato.",
     ""),
    ("P09-T16", 1, "Tirar a credencial WordPress do CLI do motor",
     "Um funnelforge --publish rodado direto no terminal ainda publica com a credencial do processo.",
     "O CLI sem autorização não recebe credencial e só a porta governada publica, com plano aprovado e recibo.",
     "P09-T15"),
    ("P09-T18", 1, "Versionar detectores e severidades do portão",
     "O fingerprint do recibo cobre as fontes, mas não regex, limiares nem tabelas de severidade.",
     "Mudar qualquer detector ou limiar muda o fingerprint e invalida recibos antigos, com teste provando.",
     "P09-T15"),
    ("P05-T13", 1, "Reauditar os destinos /r antes de voltar a pagar mídia",
     "Oito destinos históricos não foram reavaliados e a causa literal da suspensão ainda não veio do Google.",
     "Cada destino pago tem recibo live aprovado e a notificação da suspensão está registrada antes de qualquer campanha voltar.",
     "P09-T15"),
    ("P10-T19", 1, "Rodar o canário do Editorial V2 no motor integrado e fazer o deploy",
     "O canário aprovado em 30/09 rodou sem o portão do destino pago. Falta repetir no motor da branch e escrever o runbook do worker do Pautador.",
     "Canário completo aprovado no motor integrado, com custo registrado, e worker publicado seguindo o runbook.",
     "P01-T12"),
    ("P10-T16", 1, "Decidir a v12_04 e a agenda dos coletores",
     "Comparar a variante da sprint last-mile com a RPC adjudicada, aplicar a v12_04 oficial com autorização e escolher n8n ou worker como agenda.",
     "v12_04 aplicada com recibo, ADR da agenda registrado e o workflow importado em cópia inativa passando no validador.",
     ""),
    ("P17-T03", 1, "Aplicar a v11_03 no Supabase oficial",
     "Produção ainda não tem as tabelas e funções criativo_render_*. Falta backup e aplicação autorizada.",
     "Backup conferido, cinco tabelas e nove funções publicadas, grants corretos e rollback testado.",
     "P02-T05"),
    ("P02-T03", 1, "Tirar as gravações do Supabase hospedado",
     "Rotinas legadas ainda escrevem no projeto hospedado, como o workflow de orientações.",
     "Nenhuma rotina ativa grava no hospedado; cada uma tem sucessor no self-hosted ou foi desligada com recibo.",
     ""),

    # ── 2. Capacidades que liberam receita e operação ───────────────────────
    ("P09-T01", 2, "Aplicar o ledger de eventos e recomendações",
     "As migrations da série v10 foram provadas em banco descartável, mas não estão no Supabase oficial.",
     "Migrations aplicadas com backup e rollback, e o primeiro evento real gravado e relido.",
     "P02-T05"),
    ("P09-T02", 2, "Fechar proposta e autorização fora do laboratório",
     "Aprovação e recibo em voo já existem no código; nada disso chega a um banco real sem a janela de aplicação.",
     "Uma proposta real é aprovada, gravada e ligada ao plano no Supabase oficial.",
     "P09-T01"),
    ("P05-T04", 2, "Confirmar os vínculos campanha × funil",
     "trafego_vinculo tem zero linhas. Confirmar exige um operador autenticado na tela.",
     "Pelo menos as campanhas ativas têm vínculo confirmado por operador e veredito gravado.",
     ""),
    ("P05-T05", 2, "Mostrar o recibo de lançamento no cockpit",
     "A aba Criar já lê o veredito do servidor, mas o cockpit ainda mostra rotas e identidades antigas e nenhuma reconciliação foi exercida.",
     "Uma campanha criada aparece no cockpit com o recibo do lançamento e o estado da reconciliação.",
     "P05-T04"),
    ("P05-T06", 2, "Ligar proposta, confirmação e recibo nas ações assistidas",
     "aoSubmeter não tem chamador em produção e o writer v10_02 não está ligado. Falta também a rota de diagnóstico.",
     "Uma ação assistida sai da proposta, passa pela confirmação humana e termina com recibo.",
     "P09-T02"),
    ("P05-T10", 2, "Decidir o lote 3 da RSA e tipar a ingestão",
     "O lote 3 do funil Senac está pronto com validate_only e rollback, mas não foi autorizado. Falta ingestão tipada e medição.",
     "O lote 3 foi aplicado ou descartado com registro, e a próxima mudança de RSA sai pelo executor com um eixo por experimento.",
     "P09-T03"),
    ("P04-T04", 2, "Provar o Display com validate_only na conta real",
     "O builder está pronto e testado com cliente falso. A prova na conta nunca rodou.",
     "Um validate_only real de Display volta sem erro e o recibo fica gravado.",
     ""),
    ("P04-T09", 2, "Fechar a prova segura do Demand Gen",
     "As recusas locais estão provadas; a mutação real continua fechada por decisão.",
     "validate_only real aceito, com selo ligado ao canal e à conta, sem abrir mutação.",
     "P04-T04"),
    ("P04-T07", 2, "Fechar a observabilidade do PMax",
     "Os fatos de canal são lidos, mas a coluna do espelho exige migration que não foi autorizada.",
     "Campanhas PMax da conta aparecem com asset groups e cobertura lidos, sem criação liberada.",
     ""),
    ("P04-T05", 2, "Ligar imagem e vídeo ao contrato de canal",
     "Falta um detector de pixel no servidor e a decisão sobre mandar bytes de criativo a terceiro.",
     "Uma peça de imagem passa pelo portão por peça com detector registrado e recibo.",
     ""),
    ("P04-T06", 2, "Mostrar inventário por canal com dado real",
     "Nenhuma campanha real foi relida numa conta viva pelas seções específicas de canal.",
     "As seções de Display, Demand Gen e PMax mostram campanhas reais relidas da conta.",
     "P04-T07"),
    ("P06-T03", 2, "Reconciliar as fontes de receita",
     "A rede GAM nova roda nos quatro workflows, mas o destino ainda é o Supabase legado, sem ledger, heartbeat nem alerta.",
     "Receita GAM grava no self-hosted, com execução registrada e alerta quando a rotina para.",
     "P02-T03"),
    ("P06-T02", 2, "Consolidar o custo por data e conta",
     "Os coletores estão corrigidos, mas inativos, e daily_campaign_metrics não tem conta, execução, moeda nem data de coleta.",
     "Custo diário por conta e campanha chega ao ledger canônico, sem ambiguidade entre contas.",
     "P10-T16"),
    ("P06-T04", 2, "Fechar moeda, câmbio, impostos e revshare",
     "Moeda, fuso e coluna de receita do GAM ainda pedem configuração por conta; sem paridade não há lucro calculado.",
     "Cada conta GAM tem moeda e fuso declarados e o retorno é calculado com regra registrada.",
     "P06-T03"),
    ("P06-T08", 2, "Escrever a v12_02 do ledger de coleta",
     "A v12_01 não representa evidência pré-lançamento e a chave colapsa escopo sem campaign_id.",
     "v12_02 escrita, provada em banco descartável e aplicada com rollback.",
     "P10-T16"),
    ("P09-T14", 2, "Ligar a coleta contínua do Google Ads",
     "Falta escolher a agenda única, ativar a frequência e dar um consumidor ao deadman.",
     "A primeira janela automática roda, grava recibo e o deadman avisa se ela parar.",
     "P10-T16"),
    ("P05-T12", 2, "Gravar o plano de mensuração do nascimento Search",
     "A tabela existe no Supabase oficial e está vazia. A conta tem ações de compra que não estão biddable na campanha do canário.",
     "O plano de mensuração da próxima campanha Search é gravado, relido e mostra a ação de conversão correta.",
     "P09-T14"),
    ("P05-T07", 2, "Completar o diagnóstico de não escala do Search",
     "Faltam termos de busca, negativas por sobrebloqueio e experimentos, e o endpoint não foi conferido campo a campo contra a resposta real.",
     "GET /diagnostico devolve todos os campos do aceite com fonte e data, conferidos contra uma campanha real.",
     "P09-T14"),
    ("P05-T08", 2, "Fechar termos e negativas nos dois sentidos",
     "Não existem negativas nem o ciclo promover, negativar, preservar e despromover a partir dos termos reais.",
     "Propostas de termo e negativa saem do SearchTermView, mostram conflito reverso e só mudam a conta pela porta única.",
     "P05-T07"),
    ("P05-T09", 2, "Colocar o guardião das 72 horas em rotina",
     "A política existe e é testada, mas nenhuma rotina grava ou resolve os incidentes.",
     "Uma campanha nova recebe constatações nas janelas de 24 e 72 horas, gravadas com evidência e data.",
     "P05-T07"),
    ("P11-T03", 2, "Fechar a integração segura do system user Meta",
     "O perfil de criação está instalado; a cadeia pack, política, registro Meta e anúncio ainda não roda.",
     "Um anúncio PAUSED é criado pela cadeia completa usando o token do secret-provider.",
     ""),
    ("P11-T02", 2, "Executar upload e canário do pack Meta",
     "A autorização de mídia restrita ao rascunho existe; o upload e o canário não rodaram e dependem de URL e pixel do operador.",
     "Um pack aprovado sobe para a conta, é relido e vira anúncio PAUSED no canário.",
     "P11-T03"),
    ("P11-T09", 2, "Registrar mídia real e revisar campanha Meta PAUSED",
     "Falta o upload com releitura real e o canário de campanha PAUSED validado pelo plano exato.",
     "Mídia registrada com releitura e uma campanha PAUSED conferida contra o plano, sem ativação.",
     "P11-T02"),
    ("P11-T05", 2, "Criar campanha, conjunto e anúncio Meta em modo seguro",
     "A criação PAUSED existe no código; o canário real não foi executado.",
     "Uma campanha completa nasce PAUSED na conta e é relida igual ao plano aprovado.",
     "P11-T09"),
    ("P11-T11", 2, "Provar identidade regulatória e retomada da criação",
     "A identidade e a retomada passam nos testes; falta o read-back do conjunto aceito pela Meta.",
     "Um conjunto com identidade escolhida é aceito pela Meta e uma criação interrompida retoma sem duplicar.",
     "P11-T05"),
    ("P11-T20", 2, "Reconciliar o grão financeiro GAM por conjunto",
     "Schema e regras estão provados; falta a primeira linha real reconciliada e o workflow remoto conferido.",
     "A primeira receita real por conjunto/dia bate com a soma da campanha.",
     "P06-T03"),
    ("P11-T25", 2, "Fechar o percurso Meta até a receita",
     "Clique, chegada, impressão GAM e receita existem na tela; falta conferir com dados reais e grão adset/dia.",
     "Um conjunto real mostra o percurso até a receita, com cobertura e confiança declaradas.",
     "P11-T20"),
    ("P17-T05", 2, "Tirar o render do processo web",
     "O worker isolado funciona em teste, mas não há host de produção e o despacho padrão ainda é inline.",
     "Um job de imagem roda no worker de produção, com lease, custo e recibo.",
     "P17-T03"),
    ("P17-T06", 2, "Criar o storage remoto com verificação de bytes",
     "O bucket privado criativos não existe e o adapter remoto não é escolhido por configuração.",
     "Um artefato sobe, é relido, o sha256 confere e só então aparece como verificado.",
     "P17-T03, P17-T05"),
    ("P11-T04", 2, "Armar o armazenamento e o custo das peças geradas",
     "ArmazenamentoSupabase está desarmado, v11_06 e v11_07 são candidatas e não há custo por asset nem ponte para a biblioteca Meta.",
     "Uma geração real sai na dimensão pedida, fica guardada com custo e chega à biblioteca Meta.",
     "P17-T06"),
    ("P17-T08", 2, "Aprovar uma peça real por destino",
     "Falta ligar o detector de texto (pytesseract no host) e fechar a metade visual de logotipos.",
     "Uma peça aprovada para Google, Meta ou orgânico tem briefing, hashes, custo, recibo e storage verificado.",
     "P17-T05, P17-T06"),
    ("P10-T20", 2, "Fechar a identidade editorial do Redator",
     "Preview autenticado em desktop e mobile, propagação editorial e medição real seguem pendentes.",
     "Um rascunho real passa nos bloqueios de imagem, HTML e aviso e é validado em preview antes da publicação humana.",
     "P10-T19"),

    # ── 3. Integrações incompletas ──────────────────────────────────────────
    ("P03-T02", 3, "Cadastrar a página Facebook monetizada no Cofre",
     "O fluxo e a ficha estão prontos; falta o operador preencher os dados reais.",
     "A página aparece no Cofre com owner, finalidade e referência segura de credencial.",
     ""),
    ("P03-T03", 3, "Inventariar contas, páginas, perfis, domínios e grupos",
     "O catálogo real ainda não existe.",
     "Cada ativo conhecido está no Cofre com owner e estado.",
     "P03-T02"),
    ("P03-T06", 3, "Ligar o Cofre ao Mapa Vivo",
     "O Cofre não lê nem escreve relações no grafo e não tem inventário real.",
     "Um ativo cadastrado aparece no grafo com as relações certas.",
     "P03-T03"),
    ("P03-T10", 3, "Persistir referências reais de credencial",
     "Nenhuma referência real foi gravada nem resolvida.",
     "Um ativo real completa a cadeia 1Password, Cofre e broker sem segredo em claro.",
     "P03-T06"),
    ("P03-T07", 3, "Inventariar os perfis AdsPower",
     "Nenhum perfil real foi cadastrado nem consultado.",
     "Um perfil do piloto tem ID de referência, owner, ativo, finalidade e credencial referenciada.",
     "P03-T10"),
    ("P03-T11", 3, "Provar o broker 1Password → AdsPower",
     "Não houve resolução real, AdsPower vivo, perfil real nem screenshot.",
     "Uma navegação real é feita pelo broker com recibo sanitizado.",
     "P03-T07"),
    ("P03-T05", 3, "Registrar o ChatPion no Cofre",
     "O endpoint responde, mas a configuração funcional não foi verificada.",
     "ChatPion cadastrado com owner e configuração conferida, sem segredo copiado.",
     ""),
    ("P06-T07", 3, "Inventariar GA4 e GTM no Tracking Control Plane",
     "Falta toda a metade de propriedades, streams, containers, tags, eventos e drift.",
     "Propriedades e containers das contas ativas aparecem lidos, com drift sinalizado.",
     ""),
    ("P07-T02", 3, "Definir o evento de conversão offline elegível",
     "O contrato da API está mapeado, mas nenhum evento foi escolhido.",
     "Evento, valor e regra de elegibilidade aprovados por escrito.",
     "P05-T12"),
    ("P07-T03", 3, "Criar a fila de conversões",
     "conversion_queue e conversion_batches são só estrutura vazia.",
     "Eventos entram na fila com chave idempotente e lotes respeitam o limite da API.",
     "P07-T02"),
    ("P07-T04", 3, "Enviar conversões em modo seguro",
     "Nenhum envio nem validate foi executado.",
     "Um lote validado é enviado e o status é reconciliado até SUCCESS ou falha lida.",
     "P07-T03"),
    ("P07-T05", 3, "Mostrar falha de envio no cockpit",
     "Sem fila e sem envio, não há falha para mostrar.",
     "O cockpit mostra o estado de cada lote e o motivo de qualquer falha.",
     "P07-T04"),
    ("P08-T02", 3, "Completar o vínculo campanha → funil → URL",
     "Parte das campanhas ainda não tem o elo completo.",
     "Toda campanha ativa tem funil e URLs ligados.",
     "P05-T04"),
    ("P08-T03", 3, "Corrigir host e path vazios na telemetria",
     "O snapshot registra fatos sem contexto completo de página.",
     "Todo evento novo traz host, path e identidade de página.",
     ""),
    ("P08-T07", 3, "Versionar a telemetria e fechar o agregador do funil",
     "O flow do agregador está inativo, duplica orquestração e tem datas fixas.",
     "Agregações reproduzíveis no Supabase oficial, com execução datada e sem data fixa.",
     "P08-T03"),
    ("P08-T06", 3, "Unificar os sinais no Topic Radar",
     "Trends, Search Console, GA4, termos, RPM, geo e sazonalidade ainda não saem numa resposta só.",
     "Um tema consultado devolve os sinais juntos, cada um com fonte e data.",
     ""),
    ("P08-T10", 3, "Exercitar a tese de oportunidade ponta a ponta",
     "O fluxo real de arrastar o card não rodou contra o Supabase oficial e o CPC ainda pesa na densidade.",
     "Um card real gera a tese no Validador e o resultado é reproduzível.",
     "P08-T06"),
    ("P08-T09", 3, "Consolidar o recomendador semântico",
     "O subflow do n8n está quebrado no match e duplica o que o Redator já faz.",
     "Um só recomendador gera links same-domain com preview, aprovação e clique medido; o outro foi desligado.",
     "P08-T02"),
    ("P09-T07", 3, "Resgatar as orientações do Supabase legado",
     "O workflow ativo ainda grava a versão 2.1 no hospedado.",
     "As orientações são geradas e gravadas no self-hosted, e o workflow legado foi desligado.",
     "P02-T03"),
    ("P10-T03", 3, "Eliminar duplicidade de métricas por fonte e data",
     "Falta ledger por execução e chave conta+campanha+data.",
     "Uma mesma data e campanha não aparece duas vezes em nenhuma tabela de métricas.",
     "P06-T08"),
    ("P10-T06", 3, "Criar o registro de pipelines sobre jobs reais",
     "Não existe contrato comum de job, execução, agenda, owner, heartbeat e último erro.",
     "Todo job ativo está no registro com último sucesso e último erro.",
     ""),
    ("P10-T08", 3, "Tirar configuração sensível dos Code nodes",
     "Workflows legados ainda carregam contas, domínios, limiares e fórmulas em JSON executável.",
     "O n8n recebe só job_id e referência de credencial, e o scanner não encontra configuração sensível.",
     "P10-T06"),
    ("P11-T06", 3, "Sincronizar a página canônica Meta com dados reais",
     "A página existe; não há sincronização real nem QA autenticado.",
     "Campanha, conjunto e anúncio reais aparecem com métricas lidas da conta.",
     "P11-T05"),
    ("P11-T15", 3, "Provar a criação PAUSED completa pelo assistente automático",
     "A preparação automática funciona em teste; falta a criação completa com criativos e QA autenticado.",
     "Um uso real do assistente cria campanha PAUSED com criativos e anúncios relidos.",
     "P11-T05"),
    ("P11-T16", 3, "Reusar post original Meta com releitura",
     "Os packs crescem sem afetar rascunhos antigos; falta QA autenticado e reuso remoto PAUSED.",
     "Um post original é reutilizado num anúncio PAUSED e relido.",
     "P11-T05"),
    ("P11-T17", 3, "Validar o contexto da LP e a montagem criativa Meta",
     "Testes antigos de páginas têm 56 falhas de navegação e o canário remoto não rodou.",
     "Um anúncio montado com contexto da LP é criado PAUSED e relido.",
     "P11-T05"),
    ("P11-T18", 3, "Aprovar a varinha de copy e a nomenclatura Meta",
     "Falta o fluxo autenticado e a aprovação da qualidade da copy pelo operador.",
     "O operador aprova a copy sugerida e os nomes reservados em uma conta real.",
     ""),
    ("P11-T19", 3, "Testar autenticado o contexto persistido da copy",
     "A revisão técnica fechou; falta o teste autenticado com a seleção exata.",
     "Uma sugestão de um clique usa o contexto certo numa sessão real, com confirmação PAUSED.",
     "P11-T18"),
    ("P11-T14", 3, "Provar o espelho Meta no Webgo",
     "Schema e RLS estão aplicados; faltam sessão autenticada e canário PAUSED.",
     "Uma sessão Webgo cria uma campanha PAUSED sem tocar dados da VOLC.",
     "P11-T05"),
    ("P12-T03", 3, "Escolher vertical e objetivo do piloto orgânico",
     "O escopo do piloto continua aberto.",
     "Vertical, página e objetivo de uma semana decididos por escrito.",
     "P03-T02"),
    ("P12-T08", 3, "Subir o Postiz isolado",
     "O pacote está validado offline; nenhum container foi iniciado.",
     "Postiz responde healthcheck, com backup e restauração provados.",
     ""),
    ("P12-T09", 3, "Provar a porta VOLC de publicação em sandbox",
     "O aceite externo em sandbox não ocorreu e IDs e URLs reais não voltaram ao job.",
     "Um post de sandbox é criado sem duplicar e o ID e a URL voltam ao job.",
     "P12-T08"),
    ("P12-T04", 3, "Levar uma peça à página orgânica real",
     "Nenhuma peça percorreu a página real e os motores externos não têm adapter de produção.",
     "Uma peça aprovada é preparada para a página do piloto com recibo.",
     "P12-T03"),
    ("P12-T05", 3, "Publicar a primeira peça orgânica com recibo",
     "Não existe recibo de publicação real.",
     "Uma publicação tem ID externo, URL reconciliada, versão, horário e recibo.",
     "P12-T04, P12-T09"),
    ("P12-T06", 3, "Medir alcance, interação e clique do orgânico",
     "O loop orgânico não tem dado real.",
     "As métricas da primeira publicação são lidas e guardadas com data.",
     "P12-T05"),
    ("P12-T11", 3, "Ligar o AdsPower ao portão visual do Redator",
     "Navegador, perfil e página reais não foram exercitados.",
     "Uma URL real gera screenshot com hash e veredito, sem expor segredo.",
     "P03-T11"),
    ("P12-T12", 3, "Fechar o piloto orgânico ponta a ponta",
     "Nenhuma página percorreu o caminho completo.",
     "Uma página real vai da pauta à métrica com screenshot e decisão seguinte registrada.",
     "P12-T05, P12-T06, P12-T11"),
    ("P13-T02", 3, "Inventariar páginas, fluxos e webhooks do ChatPion",
     "A configuração funcional não foi observada.",
     "Páginas, fluxos, webhooks e permissões listados.",
     "P03-T05"),
    ("P13-T03", 3, "Escolher um canal de retorno para o piloto",
     "Push, e-mail, SMS, WhatsApp e Telegram ainda disputam o mesmo espaço.",
     "Um canal escolhido por escrito, com motivo.",
     "P13-T02"),
    ("P13-T04", 3, "Definir consentimento, opt-out, frequência e logs",
     "O portão de consentimento não existe.",
     "Regras escritas e testadas antes do primeiro envio.",
     "P13-T03"),
    ("P13-T05", 3, "Exportar e auditar o workflow de promoções",
     "A rota direta não permitiu inspecionar o fluxo.",
     "Workflow exportado sem segredo e auditado.",
     ""),
    ("P13-T06", 3, "Provar uma oferta afiliada com atribuição",
     "Mercado Livre e Amazon continuam hipótese.",
     "Uma oferta real com clique e conversão atribuídos.",
     "P13-T05"),

    # ── 4. Qualidade e confiabilidade ───────────────────────────────────────
    ("P10-T04", 4, "Dar consumidor ao deadman",
     "O deadman existe e é testado, mas nenhuma rota ou tela o consulta e a view que ele lê depende da v12_04.",
     "Uma coleta parada aparece como atrasada ou falhou na tela, com última tentativa e último sucesso separados.",
     "P10-T16"),
    ("P06-T05", 4, "Persistir os alertas de rotina parada",
     "consolidar() não tem chamador produtivo, persistência nem heartbeat.",
     "Um incidente de entrega é gravado, repetido e resolvido com histórico.",
     "P10-T04"),
    ("P06-T06", 4, "Fechar o Ads Health Monitor mínimo",
     "A fila de atenção ainda projeta o sintoma do inventário e não consome o incidente da sentinela.",
     "A fila mostra os incidentes da sentinela por conta, com visão de carteira.",
     "P06-T05"),
    ("P02-T04", 4, "Dar recibo, owner e heartbeat a cada rotina",
     "O caminho ativo usa SQLite local e o contrato não cobre ORAKUL, n8n e os demais jobs.",
     "Toda rotina ativa tem owner, heartbeat e recibo no registro de pipelines.",
     "P10-T06"),
    ("P10-T02", 4, "Classificar os workflows pelo que rodou, não pelo declarado",
     "Parte do inventário ainda usa estado declarado.",
     "Cada workflow está como ativo, dormente, quebrado, histórico ou futuro com base em execução observada.",
     "P10-T06"),
    ("P10-T15", 4, "Automatizar o gate de curadoria pós-integração",
     "O protocolo existe, mas o curador único não consome o handoff sozinho nem publica recibo no QG.",
     "Depois de um merge, o QG mostra o recibo da curadoria com tarefas, nós e frescor.",
     "P10-T06"),
    ("P17-T07", 4, "Decidir a licença do Remotion e fechar o render hermético",
     "Falta a decisão de licença e a prova de equivalência macOS e Linux.",
     "Licença registrada e o mesmo hash de vídeo reproduzido no host de produção.",
     "P17-T05"),

    # ── 5. Acabamento e menor impacto ───────────────────────────────────────
    ("P04-T08", 5, "Comparar Adios, Copycat e Vigenair com os motores próprios",
     "Faltam matrizes de capacidade, custo, linhagem, aprovação e destino.",
     "Uma matriz decidida diz o que adotar, adaptar ou descartar.",
     ""),
    ("P08-T04", 5, "Modelar tema como conjunto de peças",
     "O conceito está curado; o modelo não existe.",
     "Um tema real é representado com suas peças e relações.",
     ""),
    ("P08-T05", 5, "Testar uma página interativa contra controle",
     "Os widgets existem sem medir resultado.",
     "Um teste com controle e variante tem resultado registrado.",
     "P08-T07"),
    ("P08-T08", 5, "Transformar a análise de CTA em experimento",
     "O flow está inativo e não mede controle contra variante.",
     "Uma hipótese de CTA vira experimento aprovado, com resultado gravado.",
     "P08-T02, P09-T03"),
    ("P09-T06", 5, "Provar um gateway agêntico Google Ads só leitura",
     "Falta o gateway no backend com escopo, contexto filtrado e logs.",
     "Uma consulta passa pelo gateway com log e sem segredo no navegador.",
     ""),
    ("P09-T04", 5, "Integrar a Bia em modo leitura",
     "Widget e gateway faltam.",
     "A Bia responde sobre uma campanha real citando fonte, sem escrever nada.",
     "P09-T06"),
    ("P09-T05", 5, "Permitir confirmação humana contextual",
     "Fase posterior ao modo leitura.",
     "Uma sugestão da Bia só segue depois da confirmação registrada.",
     "P09-T04"),
    ("P09-T08", 5, "Extrair o kernel ORAKUL para políticas versionadas",
     "A lógica histórica ainda está misturada a I/O em 1.678 linhas.",
     "Pacote puro com replay que reproduz ou explica as divergências.",
     "P09-T01"),
    ("P09-T09", 5, "Rodar o ORAKUL em shadow",
     "Nenhum dado real atravessou a fronteira.",
     "Shadow sobre uma janela real, com falso positivo e drawdown medidos.",
     "P09-T08"),
    ("P09-T10", 5, "Fechar o contrato econômico do allocator",
     "Não há snapshot de portfólio, ROI oficial nem moeda e janela fechadas.",
     "Snapshot imutável por período com métrica econômica aprovada.",
     "P06-T03, P06-T04"),
    ("P09-T11", 5, "Provar o allocator em replay",
     "Nenhum allocator foi implementado.",
     "Replay determinístico lado a lado com as linhas de base.",
     "P09-T10"),
    ("P09-T12", 5, "Persistir plano-pai de alocação",
     "Não existe plano de portfólio que preserve os totais.",
     "Plano-pai e propostas filhas gravados e reproduzíveis.",
     "P09-T11"),
    ("P09-T13", 5, "Rodar o allocator em shadow com propostas",
     "Depende de contrato, replay e plano-pai.",
     "Propostas do allocator aparecem no QG em shadow, com confirmação humana.",
     "P09-T12"),
    ("P10-T05", 5, "Arquivar os workflows BEAST",
     "A decisão de reuso está aberta.",
     "Cada workflow BEAST arquivado ou reaproveitado, com o contrato útil guardado.",
     ""),
    ("P10-T10", 5, "Fechar a prova ADK + DeepSeek",
     "A copy reparada não teve aceite humano em nenhum dos quatro casos.",
     "Dez repetições com pelo menos nove decisões aceitas por revisão humana.",
     ""),
    ("P10-T11", 5, "Ligar a recuperação limitada ao Redator",
     "Nenhum runtime agêntico participa das execuções.",
     "Uma falha real do Redator é recuperada em até três tentativas, com recibo.",
     "P10-T10, P10-T04"),
    ("P10-T12", 5, "Comparar o analista agêntico com o motor determinístico",
     "Falta a comparação humana sobre o mesmo snapshot.",
     "Avaliação escrita comparando os dois sobre a mesma conta.",
     "P10-T10"),
    ("P10-T13", 5, "Criar o ledger do runtime agêntico",
     "Não existe schema nem painel.",
     "Cada execução agêntica fica registrada com custo e veredito.",
     "P10-T10"),
    ("P10-T14", 5, "Montar a equipe de microreparo",
     "Não há separação entre triagem, proposta, crítica e escalada.",
     "Registro de agentes e receitas versionado, com revisor semântico separado.",
     "P10-T13"),
    ("P11-T21", 5, "Fechar o refino Meta com ADK e Gemini",
     "1,26 milhão de tokens e nenhuma edição aceita.",
     "Uma edição proposta pelo loop é aceita, testada e integrada.",
     ""),
    ("P11-T22", 5, "Aprovar a direção tipográfica PRENSA v2",
     "Falta a preferência visual do operador.",
     "O operador escolhe a direção v2 nas oito peças, sem regressão no caminho antigo.",
     ""),
]
