-- =====================================================================
-- v7 PAUTADOR PRO — Etapa 4 / SEED dos 195 PAÍSES SOBERANOS (ADITIVO, idempotente)
-- 193 Estados-membros da ONU + Santa Sé (Vaticano) + Estado da Palestina.
-- AUTO-GERADO por backend/scripts/gen_country_artifacts.py — NÃO editar à mão.
--
-- NÃO destrutivo: ON CONFLICT (country_code) DO UPDATE (não apaga países).
-- Preserva RLS/policies de v7_01. Roda DEPOIS de v7_01.
-- >>> Rodar manualmente no Supabase SQL Editor (projeto txvvzpstquqmbhljudfn). <<<
-- =====================================================================

-- 1) Colunas faltantes (idempotente)
ALTER TABLE public.pautador_countries
    ADD COLUMN IF NOT EXISTS iso3                  text,
    ADD COLUMN IF NOT EXISTS name_en               text,
    ADD COLUMN IF NOT EXISTS name_native           text,
    ADD COLUMN IF NOT EXISTS language_code         text,
    ADD COLUMN IF NOT EXISTS language_short        text,
    ADD COLUMN IF NOT EXISTS language_constant     integer,
    ADD COLUMN IF NOT EXISTS google_ads_geo_target integer,
    ADD COLUMN IF NOT EXISTS currency_code         text,
    ADD COLUMN IF NOT EXISTS aliases               jsonb NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS is_sovereign          boolean NOT NULL DEFAULT true;

CREATE INDEX IF NOT EXISTS idx_pautador_countries_iso3      ON public.pautador_countries (iso3);
CREATE INDEX IF NOT EXISTS idx_pautador_countries_sovereign ON public.pautador_countries (is_sovereign);

-- 2) Upsert dos 195 países soberanos
INSERT INTO public.pautador_countries
    (country_code, country_name, native_language, market_tier, rpm_index, flag_emoji, is_active,
     iso3, name_en, name_native, language_code, language_short, language_constant,
     google_ads_geo_target, currency_code, aliases, is_sovereign)
VALUES
    ('AF', 'Afeganistão', 'fa-AF', 'volume_play', 20, '🇦🇫', true, 'AFG', 'Afghanistan', 'افغانستان', 'fa', 'fa', NULL, NULL, 'AFN', '["af", "afeganistao", "afg", "afghanistan", "افغانستان"]'::jsonb, true),
    ('AL', 'Albânia', 'sq-AL', 'volume_play', 20, '🇦🇱', true, 'ALB', 'Albania', 'Shqipëria', 'sq', 'sq', NULL, NULL, 'ALL', '["al", "alb", "albania", "shqiperia"]'::jsonb, true),
    ('DZ', 'Argélia', 'ar-DZ', 'volume_play', 20, '🇩🇿', true, 'DZA', 'Algeria', 'الجزائر', 'ar', 'ar', 1019, NULL, 'DZD', '["algeria", "argelia", "dz", "dza", "الجزاير"]'::jsonb, true),
    ('AD', 'Andorra', 'ca-AD', 'medium_value', 50, '🇦🇩', true, 'AND', 'Andorra', 'Andorra', 'ca', 'ca', NULL, NULL, 'EUR', '["ad", "and", "andorra"]'::jsonb, true),
    ('AO', 'Angola', 'pt-AO', 'volume_play', 20, '🇦🇴', true, 'AGO', 'Angola', 'Angola', 'pt', 'pt', 1014, NULL, 'AOA', '["ago", "angola", "ao"]'::jsonb, true),
    ('AG', 'Antígua e Barbuda', 'en-AG', 'volume_play', 20, '🇦🇬', true, 'ATG', 'Antigua and Barbuda', 'Antigua and Barbuda', 'en', 'en', 1000, NULL, 'XCD', '["ag", "antigua", "antigua and barbuda", "antigua e barbuda", "atg"]'::jsonb, true),
    ('AR', 'Argentina', 'es-AR', 'medium_value', 50, '🇦🇷', true, 'ARG', 'Argentina', 'Argentina', 'es', 'es', 1003, 2032, 'ARS', '["ar", "arg", "argentina"]'::jsonb, true),
    ('AM', 'Armênia', 'hy-AM', 'volume_play', 20, '🇦🇲', true, 'ARM', 'Armenia', 'Հայաստան', 'hy', 'hy', NULL, NULL, 'AMD', '["am", "arm", "armenia", "հայաստան"]'::jsonb, true),
    ('AU', 'Austrália', 'en-AU', 'high_value', 90, '🇦🇺', true, 'AUS', 'Australia', 'Australia', 'en', 'en', 1000, 2036, 'AUD', '["au", "aus", "australia"]'::jsonb, true),
    ('AT', 'Áustria', 'de-AT', 'high_value', 90, '🇦🇹', true, 'AUT', 'Austria', 'Österreich', 'de', 'de', 1001, 2040, 'EUR', '["at", "austria", "aut", "osterreich"]'::jsonb, true),
    ('AZ', 'Azerbaijão', 'az-AZ', 'volume_play', 20, '🇦🇿', true, 'AZE', 'Azerbaijan', 'Azərbaycan', 'az', 'az', NULL, NULL, 'AZN', '["az", "aze", "azerbaijan", "azerbaijao", "azərbaycan"]'::jsonb, true),
    ('BS', 'Bahamas', 'en-BS', 'medium_value', 50, '🇧🇸', true, 'BHS', 'Bahamas', 'Bahamas', 'en', 'en', 1000, NULL, 'BSD', '["bahamas", "bhs", "bs"]'::jsonb, true),
    ('BH', 'Bahrein', 'ar-BH', 'medium_value', 50, '🇧🇭', true, 'BHR', 'Bahrain', 'البحرين', 'ar', 'ar', 1019, NULL, 'BHD', '["bahrain", "bahrein", "bh", "bhr", "البحرين"]'::jsonb, true),
    ('BD', 'Bangladesh', 'bn-BD', 'volume_play', 20, '🇧🇩', true, 'BGD', 'Bangladesh', 'বাংলাদেশ', 'bn', 'bn', NULL, NULL, 'BDT', '["bangladesh", "bd", "bgd", "বাংলাদেশ"]'::jsonb, true),
    ('BB', 'Barbados', 'en-BB', 'volume_play', 20, '🇧🇧', true, 'BRB', 'Barbados', 'Barbados', 'en', 'en', 1000, NULL, 'BBD', '["barbados", "bb", "brb"]'::jsonb, true),
    ('BY', 'Belarus', 'be-BY', 'volume_play', 20, '🇧🇾', true, 'BLR', 'Belarus', 'Беларусь', 'be', 'be', NULL, NULL, 'BYN', '["belarus", "bielorrussia", "blr", "by", "беларусь"]'::jsonb, true),
    ('BE', 'Bélgica', 'nl-BE', 'high_value', 90, '🇧🇪', true, 'BEL', 'Belgium', 'België', 'nl', 'nl', 1010, 2056, 'EUR', '["be", "bel", "belgica", "belgie", "belgium"]'::jsonb, true),
    ('BZ', 'Belize', 'en-BZ', 'volume_play', 20, '🇧🇿', true, 'BLZ', 'Belize', 'Belize', 'en', 'en', 1000, NULL, 'BZD', '["belize", "blz", "bz"]'::jsonb, true),
    ('BJ', 'Benin', 'fr-BJ', 'volume_play', 20, '🇧🇯', true, 'BEN', 'Benin', 'Bénin', 'fr', 'fr', 1002, NULL, 'XOF', '["ben", "benin", "bj"]'::jsonb, true),
    ('BT', 'Butão', 'dz-BT', 'volume_play', 20, '🇧🇹', true, 'BTN', 'Bhutan', 'འབྲུག', 'dz', 'dz', NULL, NULL, 'BTN', '["bhutan", "bt", "btn", "butao", "འབག"]'::jsonb, true),
    ('BO', 'Bolívia', 'es-BO', 'volume_play', 20, '🇧🇴', true, 'BOL', 'Bolivia', 'Bolivia', 'es', 'es', 1003, 2068, 'BOB', '["bo", "bol", "bolivia"]'::jsonb, true),
    ('BA', 'Bósnia e Herzegovina', 'bs-BA', 'volume_play', 20, '🇧🇦', true, 'BIH', 'Bosnia and Herzegovina', 'Bosna i Hercegovina', 'bs', 'bs', NULL, NULL, 'BAM', '["ba", "bih", "bosna i hercegovina", "bosnia", "bosnia and herzegovina", "bosnia e herzegovina"]'::jsonb, true),
    ('BW', 'Botsuana', 'en-BW', 'volume_play', 20, '🇧🇼', true, 'BWA', 'Botswana', 'Botswana', 'en', 'en', 1000, NULL, 'BWP', '["botsuana", "botswana", "bw", "bwa"]'::jsonb, true),
    ('BR', 'Brasil', 'pt-BR', 'medium_value', 50, '🇧🇷', true, 'BRA', 'Brazil', 'Brasil', 'pt', 'pt', 1014, 2076, 'BRL', '["br", "bra", "brasil", "brazil"]'::jsonb, true),
    ('BN', 'Brunei', 'ms-BN', 'medium_value', 50, '🇧🇳', true, 'BRN', 'Brunei', 'Brunei Darussalam', 'ms', 'ms', NULL, NULL, 'BND', '["bn", "brn", "brunei", "brunei darussalam"]'::jsonb, true),
    ('BG', 'Bulgária', 'bg-BG', 'medium_value', 50, '🇧🇬', true, 'BGR', 'Bulgaria', 'България', 'bg', 'bg', 1020, NULL, 'BGN', '["bg", "bgr", "bulgaria", "българия"]'::jsonb, true),
    ('BF', 'Burquina Faso', 'fr-BF', 'volume_play', 20, '🇧🇫', true, 'BFA', 'Burkina Faso', 'Burkina Faso', 'fr', 'fr', 1002, NULL, 'XOF', '["bf", "bfa", "burkina faso", "burquina faso"]'::jsonb, true),
    ('BI', 'Burúndi', 'fr-BI', 'volume_play', 20, '🇧🇮', true, 'BDI', 'Burundi', 'Burundi', 'fr', 'fr', 1002, NULL, 'BIF', '["bdi", "bi", "burundi"]'::jsonb, true),
    ('CV', 'Cabo Verde', 'pt-CV', 'volume_play', 20, '🇨🇻', true, 'CPV', 'Cabo Verde', 'Cabo Verde', 'pt', 'pt', 1014, NULL, 'CVE', '["cabo verde", "cape verde", "cpv", "cv"]'::jsonb, true),
    ('KH', 'Camboja', 'km-KH', 'volume_play', 20, '🇰🇭', true, 'KHM', 'Cambodia', 'កម្ពុជា', 'km', 'km', NULL, NULL, 'KHR', '["cambodia", "camboja", "kh", "khm", "កមពជា"]'::jsonb, true),
    ('CM', 'Camarões', 'fr-CM', 'volume_play', 20, '🇨🇲', true, 'CMR', 'Cameroon', 'Cameroun', 'fr', 'fr', 1002, NULL, 'XAF', '["camaroes", "cameroon", "cameroun", "cm", "cmr"]'::jsonb, true),
    ('CA', 'Canadá', 'en-CA', 'high_value', 90, '🇨🇦', true, 'CAN', 'Canada', 'Canada', 'en', 'en', 1000, 2124, 'CAD', '["ca", "can", "canada"]'::jsonb, true),
    ('CF', 'República Centro-Africana', 'fr-CF', 'volume_play', 20, '🇨🇫', true, 'CAF', 'Central African Republic', 'République centrafricaine', 'fr', 'fr', 1002, NULL, 'XAF', '["caf", "central african republic", "cf", "republica centro-africana", "republique centrafricaine"]'::jsonb, true),
    ('TD', 'Chade', 'fr-TD', 'volume_play', 20, '🇹🇩', true, 'TCD', 'Chad', 'Tchad', 'fr', 'fr', 1002, NULL, 'XAF', '["chad", "chade", "tcd", "tchad", "td"]'::jsonb, true),
    ('CL', 'Chile', 'es-CL', 'medium_value', 50, '🇨🇱', true, 'CHL', 'Chile', 'Chile', 'es', 'es', 1003, 2152, 'CLP', '["chile", "chl", "cl"]'::jsonb, true),
    ('CN', 'China', 'zh-CN', 'medium_value', 50, '🇨🇳', true, 'CHN', 'China', '中国', 'zh', 'zh', 1017, 2156, 'CNY', '["china", "chn", "cn", "中国"]'::jsonb, true),
    ('CO', 'Colômbia', 'es-CO', 'medium_value', 50, '🇨🇴', true, 'COL', 'Colombia', 'Colombia', 'es', 'es', 1003, 2170, 'COP', '["co", "col", "colombia"]'::jsonb, true),
    ('KM', 'Comores', 'fr-KM', 'volume_play', 20, '🇰🇲', true, 'COM', 'Comoros', 'Comores', 'fr', 'fr', 1002, NULL, 'KMF', '["com", "comores", "comoros", "km"]'::jsonb, true),
    ('CG', 'Congo', 'fr-CG', 'volume_play', 20, '🇨🇬', true, 'COG', 'Republic of the Congo', 'Congo', 'fr', 'fr', 1002, NULL, 'XAF', '["cg", "cog", "congo", "congo brazzaville", "republic of the congo"]'::jsonb, true),
    ('CD', 'República Democrática do Congo', 'fr-CD', 'volume_play', 20, '🇨🇩', true, 'COD', 'DR Congo', 'RD Congo', 'fr', 'fr', 1002, NULL, 'CDF', '["cd", "cod", "congo kinshasa", "democratic republic of the congo", "dr congo", "rd congo", "rdc", "republica democratica do congo"]'::jsonb, true),
    ('CR', 'Costa Rica', 'es-CR', 'medium_value', 50, '🇨🇷', true, 'CRI', 'Costa Rica', 'Costa Rica', 'es', 'es', 1003, NULL, 'CRC', '["costa rica", "cr", "cri"]'::jsonb, true),
    ('CI', 'Costa do Marfim', 'fr-CI', 'volume_play', 20, '🇨🇮', true, 'CIV', 'Ivory Coast', 'Côte d''Ivoire', 'fr', 'fr', 1002, NULL, 'XOF', '["ci", "civ", "costa do marfim", "cote d ivoire", "cote d''ivoire", "ivory coast"]'::jsonb, true),
    ('HR', 'Croácia', 'hr-HR', 'medium_value', 50, '🇭🇷', true, 'HRV', 'Croatia', 'Hrvatska', 'hr', 'hr', 1039, NULL, 'EUR', '["croacia", "croatia", "hr", "hrv", "hrvatska"]'::jsonb, true),
    ('CU', 'Cuba', 'es-CU', 'volume_play', 20, '🇨🇺', true, 'CUB', 'Cuba', 'Cuba', 'es', 'es', 1003, NULL, 'CUP', '["cu", "cub", "cuba"]'::jsonb, true),
    ('CY', 'Chipre', 'el-CY', 'medium_value', 50, '🇨🇾', true, 'CYP', 'Cyprus', 'Κύπρος', 'el', 'el', 1022, NULL, 'EUR', '["chipre", "cy", "cyp", "cyprus", "κυπρος"]'::jsonb, true),
    ('CZ', 'Tchéquia', 'cs-CZ', 'medium_value', 50, '🇨🇿', true, 'CZE', 'Czechia', 'Česko', 'cs', 'cs', 1021, 2203, 'CZK', '["cesko", "cz", "cze", "czech republic", "czechia", "republica tcheca", "tchequia"]'::jsonb, true),
    ('DK', 'Dinamarca', 'da-DK', 'high_value', 90, '🇩🇰', true, 'DNK', 'Denmark', 'Danmark', 'da', 'da', 1009, 2208, 'DKK', '["danmark", "denmark", "dinamarca", "dk", "dnk"]'::jsonb, true),
    ('DJ', 'Djibuti', 'fr-DJ', 'volume_play', 20, '🇩🇯', true, 'DJI', 'Djibouti', 'Djibouti', 'fr', 'fr', 1002, NULL, 'DJF', '["dj", "dji", "djibouti", "djibuti"]'::jsonb, true),
    ('DM', 'Dominica', 'en-DM', 'volume_play', 20, '🇩🇲', true, 'DMA', 'Dominica', 'Dominica', 'en', 'en', 1000, NULL, 'XCD', '["dm", "dma", "dominica"]'::jsonb, true),
    ('DO', 'República Dominicana', 'es-DO', 'medium_value', 50, '🇩🇴', true, 'DOM', 'Dominican Republic', 'República Dominicana', 'es', 'es', 1003, NULL, 'DOP', '["do", "dom", "dominican republic", "republica dominicana"]'::jsonb, true),
    ('EC', 'Equador', 'es-EC', 'volume_play', 20, '🇪🇨', true, 'ECU', 'Ecuador', 'Ecuador', 'es', 'es', 1003, 2218, 'USD', '["ec", "ecu", "ecuador", "equador"]'::jsonb, true),
    ('EG', 'Egito', 'ar-EG', 'medium_value', 50, '🇪🇬', true, 'EGY', 'Egypt', 'مصر', 'ar', 'ar', 1019, 2818, 'EGP', '["eg", "egito", "egy", "egypt", "مصر"]'::jsonb, true),
    ('SV', 'El Salvador', 'es-SV', 'volume_play', 20, '🇸🇻', true, 'SLV', 'El Salvador', 'El Salvador', 'es', 'es', 1003, NULL, 'USD', '["el salvador", "slv", "sv"]'::jsonb, true),
    ('GQ', 'Guiné Equatorial', 'es-GQ', 'volume_play', 20, '🇬🇶', true, 'GNQ', 'Equatorial Guinea', 'Guinea Ecuatorial', 'es', 'es', 1003, NULL, 'XAF', '["equatorial guinea", "gnq", "gq", "guine equatorial", "guinea ecuatorial"]'::jsonb, true),
    ('ER', 'Eritreia', 'ti-ER', 'volume_play', 20, '🇪🇷', true, 'ERI', 'Eritrea', 'Eritrea', 'ti', 'ti', NULL, NULL, 'ERN', '["er", "eri", "eritrea", "eritreia"]'::jsonb, true),
    ('EE', 'Estônia', 'et-EE', 'medium_value', 50, '🇪🇪', true, 'EST', 'Estonia', 'Eesti', 'et', 'et', NULL, NULL, 'EUR', '["ee", "eesti", "est", "estonia"]'::jsonb, true),
    ('SZ', 'Essuatíni', 'en-SZ', 'volume_play', 20, '🇸🇿', true, 'SWZ', 'Eswatini', 'eSwatini', 'en', 'en', 1000, NULL, 'SZL', '["essuatini", "eswatini", "suazilandia", "swaziland", "swz", "sz"]'::jsonb, true),
    ('ET', 'Etiópia', 'am-ET', 'volume_play', 20, '🇪🇹', true, 'ETH', 'Ethiopia', 'ኢትዮጵያ', 'am', 'am', NULL, NULL, 'ETB', '["et", "eth", "ethiopia", "etiopia", "ኢትዮጵያ"]'::jsonb, true),
    ('FJ', 'Fiji', 'en-FJ', 'volume_play', 20, '🇫🇯', true, 'FJI', 'Fiji', 'Fiji', 'en', 'en', 1000, NULL, 'FJD', '["fiji", "fj", "fji"]'::jsonb, true),
    ('FI', 'Finlândia', 'fi-FI', 'high_value', 90, '🇫🇮', true, 'FIN', 'Finland', 'Suomi', 'fi', 'fi', 1011, 2246, 'EUR', '["fi", "fin", "finland", "finlandia", "suomi"]'::jsonb, true),
    ('FR', 'França', 'fr-FR', 'high_value', 90, '🇫🇷', true, 'FRA', 'France', 'France', 'fr', 'fr', 1002, 2250, 'EUR', '["fr", "fra", "franca", "france"]'::jsonb, true),
    ('GA', 'Gabão', 'fr-GA', 'volume_play', 20, '🇬🇦', true, 'GAB', 'Gabon', 'Gabon', 'fr', 'fr', 1002, NULL, 'XAF', '["ga", "gab", "gabao", "gabon"]'::jsonb, true),
    ('GM', 'Gâmbia', 'en-GM', 'volume_play', 20, '🇬🇲', true, 'GMB', 'Gambia', 'Gambia', 'en', 'en', 1000, NULL, 'GMD', '["gambia", "gm", "gmb"]'::jsonb, true),
    ('GE', 'Geórgia', 'ka-GE', 'volume_play', 20, '🇬🇪', true, 'GEO', 'Georgia', 'საქართველო', 'ka', 'ka', NULL, NULL, 'GEL', '["ge", "geo", "georgia", "საქართველო"]'::jsonb, true),
    ('DE', 'Alemanha', 'de-DE', 'high_value', 90, '🇩🇪', true, 'DEU', 'Germany', 'Deutschland', 'de', 'de', 1001, 2276, 'EUR', '["alemanha", "de", "deu", "deutschland", "germany"]'::jsonb, true),
    ('GH', 'Gana', 'en-GH', 'volume_play', 20, '🇬🇭', true, 'GHA', 'Ghana', 'Ghana', 'en', 'en', 1000, NULL, 'GHS', '["gana", "gh", "gha", "ghana"]'::jsonb, true),
    ('GR', 'Grécia', 'el-GR', 'medium_value', 50, '🇬🇷', true, 'GRC', 'Greece', 'Ελλάδα', 'el', 'el', 1022, 2300, 'EUR', '["gr", "grc", "grecia", "greece", "ελλαδα"]'::jsonb, true),
    ('GD', 'Granada', 'en-GD', 'volume_play', 20, '🇬🇩', true, 'GRD', 'Grenada', 'Grenada', 'en', 'en', 1000, NULL, 'XCD', '["gd", "granada", "grd", "grenada"]'::jsonb, true),
    ('GT', 'Guatemala', 'es-GT', 'volume_play', 20, '🇬🇹', true, 'GTM', 'Guatemala', 'Guatemala', 'es', 'es', 1003, 2320, 'GTQ', '["gt", "gtm", "guatemala"]'::jsonb, true),
    ('GN', 'Guiné', 'fr-GN', 'volume_play', 20, '🇬🇳', true, 'GIN', 'Guinea', 'Guinée', 'fr', 'fr', 1002, NULL, 'GNF', '["gin", "gn", "guine", "guinea", "guinee"]'::jsonb, true),
    ('GW', 'Guiné-Bissau', 'pt-GW', 'volume_play', 20, '🇬🇼', true, 'GNB', 'Guinea-Bissau', 'Guiné-Bissau', 'pt', 'pt', 1014, NULL, 'XOF', '["gnb", "guine-bissau", "guinea bissau", "guinea-bissau", "gw"]'::jsonb, true),
    ('GY', 'Guiana', 'en-GY', 'volume_play', 20, '🇬🇾', true, 'GUY', 'Guyana', 'Guyana', 'en', 'en', 1000, NULL, 'GYD', '["guiana", "guy", "guyana", "gy"]'::jsonb, true),
    ('HT', 'Haiti', 'fr-HT', 'volume_play', 20, '🇭🇹', true, 'HTI', 'Haiti', 'Haïti', 'fr', 'fr', 1002, NULL, 'HTG', '["haiti", "ht", "hti"]'::jsonb, true),
    ('HN', 'Honduras', 'es-HN', 'volume_play', 20, '🇭🇳', true, 'HND', 'Honduras', 'Honduras', 'es', 'es', 1003, NULL, 'HNL', '["hn", "hnd", "honduras"]'::jsonb, true),
    ('HU', 'Hungria', 'hu-HU', 'medium_value', 50, '🇭🇺', true, 'HUN', 'Hungary', 'Magyarország', 'hu', 'hu', 1024, 2348, 'HUF', '["hu", "hun", "hungary", "hungria", "magyarorszag"]'::jsonb, true),
    ('IS', 'Islândia', 'is-IS', 'high_value', 90, '🇮🇸', true, 'ISL', 'Iceland', 'Ísland', 'is', 'is', NULL, NULL, 'ISK', '["iceland", "is", "isl", "island", "islandia"]'::jsonb, true),
    ('IN', 'Índia', 'hi-IN', 'volume_play', 20, '🇮🇳', true, 'IND', 'India', 'भारत', 'hi', 'hi', 1023, 2356, 'INR', '["in", "ind", "india", "भारत"]'::jsonb, true),
    ('ID', 'Indonésia', 'id-ID', 'volume_play', 20, '🇮🇩', true, 'IDN', 'Indonesia', 'Indonesia', 'id', 'id', 1025, 2360, 'IDR', '["id", "idn", "indonesia"]'::jsonb, true),
    ('IR', 'Irã', 'fa-IR', 'volume_play', 20, '🇮🇷', true, 'IRN', 'Iran', 'ایران', 'fa', 'fa', NULL, NULL, 'IRR', '["ir", "ira", "iran", "irn", "ایران"]'::jsonb, true),
    ('IQ', 'Iraque', 'ar-IQ', 'volume_play', 20, '🇮🇶', true, 'IRQ', 'Iraq', 'العراق', 'ar', 'ar', 1019, NULL, 'IQD', '["iq", "iraq", "iraque", "irq", "العراق"]'::jsonb, true),
    ('IE', 'Irlanda', 'en-IE', 'high_value', 90, '🇮🇪', true, 'IRL', 'Ireland', 'Éire', 'en', 'en', 1000, 2372, 'EUR', '["eire", "ie", "ireland", "irl", "irlanda"]'::jsonb, true),
    ('IL', 'Israel', 'he-IL', 'high_value', 90, '🇮🇱', true, 'ISR', 'Israel', 'ישראל', 'he', 'he', 1027, 2376, 'ILS', '["il", "isr", "israel", "ישראל"]'::jsonb, true),
    ('IT', 'Itália', 'it-IT', 'medium_value', 50, '🇮🇹', true, 'ITA', 'Italy', 'Italia', 'it', 'it', 1004, 2380, 'EUR', '["it", "ita", "italia", "italy"]'::jsonb, true),
    ('JM', 'Jamaica', 'en-JM', 'volume_play', 20, '🇯🇲', true, 'JAM', 'Jamaica', 'Jamaica', 'en', 'en', 1000, NULL, 'JMD', '["jam", "jamaica", "jm"]'::jsonb, true),
    ('JP', 'Japão', 'ja-JP', 'high_value', 90, '🇯🇵', true, 'JPN', 'Japan', '日本', 'ja', 'ja', 1005, 2392, 'JPY', '["japan", "japao", "jp", "jpn", "日本"]'::jsonb, true),
    ('JO', 'Jordânia', 'ar-JO', 'medium_value', 50, '🇯🇴', true, 'JOR', 'Jordan', 'الأردن', 'ar', 'ar', 1019, NULL, 'JOD', '["jo", "jor", "jordan", "jordania", "الاردن"]'::jsonb, true),
    ('KZ', 'Cazaquistão', 'kk-KZ', 'medium_value', 50, '🇰🇿', true, 'KAZ', 'Kazakhstan', 'Қазақстан', 'kk', 'kk', NULL, NULL, 'KZT', '["cazaquistao", "kaz", "kazakhstan", "kz", "қазақстан"]'::jsonb, true),
    ('KE', 'Quênia', 'sw-KE', 'volume_play', 20, '🇰🇪', true, 'KEN', 'Kenya', 'Kenya', 'sw', 'sw', NULL, 2404, 'KES', '["ke", "ken", "kenya", "quenia"]'::jsonb, true),
    ('KI', 'Quiribati', 'en-KI', 'volume_play', 20, '🇰🇮', true, 'KIR', 'Kiribati', 'Kiribati', 'en', 'en', 1000, NULL, 'AUD', '["ki", "kir", "kiribati", "quiribati"]'::jsonb, true),
    ('KW', 'Kuwait', 'ar-KW', 'medium_value', 50, '🇰🇼', true, 'KWT', 'Kuwait', 'الكويت', 'ar', 'ar', 1019, NULL, 'KWD', '["kuwait", "kw", "kwt", "الكويت"]'::jsonb, true),
    ('KG', 'Quirguistão', 'ky-KG', 'volume_play', 20, '🇰🇬', true, 'KGZ', 'Kyrgyzstan', 'Кыргызстан', 'ky', 'ky', NULL, NULL, 'KGS', '["kg", "kgz", "kyrgyzstan", "quirguistao", "кыргызстан"]'::jsonb, true),
    ('LA', 'Laos', 'lo-LA', 'volume_play', 20, '🇱🇦', true, 'LAO', 'Laos', 'ລາວ', 'lo', 'lo', NULL, NULL, 'LAK', '["la", "lao", "laos", "ລາວ"]'::jsonb, true),
    ('LV', 'Letônia', 'lv-LV', 'medium_value', 50, '🇱🇻', true, 'LVA', 'Latvia', 'Latvija', 'lv', 'lv', NULL, NULL, 'EUR', '["latvia", "latvija", "letonia", "lv", "lva"]'::jsonb, true),
    ('LB', 'Líbano', 'ar-LB', 'volume_play', 20, '🇱🇧', true, 'LBN', 'Lebanon', 'لبنان', 'ar', 'ar', 1019, NULL, 'LBP', '["lb", "lbn", "lebanon", "libano", "لبنان"]'::jsonb, true),
    ('LS', 'Lesoto', 'en-LS', 'volume_play', 20, '🇱🇸', true, 'LSO', 'Lesotho', 'Lesotho', 'en', 'en', 1000, NULL, 'LSL', '["lesotho", "lesoto", "ls", "lso"]'::jsonb, true),
    ('LR', 'Libéria', 'en-LR', 'volume_play', 20, '🇱🇷', true, 'LBR', 'Liberia', 'Liberia', 'en', 'en', 1000, NULL, 'LRD', '["lbr", "liberia", "lr"]'::jsonb, true),
    ('LY', 'Líbia', 'ar-LY', 'volume_play', 20, '🇱🇾', true, 'LBY', 'Libya', 'ليبيا', 'ar', 'ar', 1019, NULL, 'LYD', '["lby", "libia", "libya", "ly", "ليبيا"]'::jsonb, true),
    ('LI', 'Liechtenstein', 'de-LI', 'high_value', 90, '🇱🇮', true, 'LIE', 'Liechtenstein', 'Liechtenstein', 'de', 'de', 1001, NULL, 'CHF', '["li", "lie", "liechtenstein"]'::jsonb, true),
    ('LT', 'Lituânia', 'lt-LT', 'medium_value', 50, '🇱🇹', true, 'LTU', 'Lithuania', 'Lietuva', 'lt', 'lt', 1029, NULL, 'EUR', '["lietuva", "lithuania", "lituania", "lt", "ltu"]'::jsonb, true),
    ('LU', 'Luxemburgo', 'fr-LU', 'high_value', 90, '🇱🇺', true, 'LUX', 'Luxembourg', 'Luxembourg', 'fr', 'fr', 1002, NULL, 'EUR', '["lu", "lux", "luxembourg", "luxemburgo"]'::jsonb, true),
    ('MG', 'Madagáscar', 'fr-MG', 'volume_play', 20, '🇲🇬', true, 'MDG', 'Madagascar', 'Madagasikara', 'fr', 'fr', 1002, NULL, 'MGA', '["madagascar", "madagasikara", "mdg", "mg"]'::jsonb, true),
    ('MW', 'Malawi', 'en-MW', 'volume_play', 20, '🇲🇼', true, 'MWI', 'Malawi', 'Malawi', 'en', 'en', 1000, NULL, 'MWK', '["malawi", "mw", "mwi"]'::jsonb, true),
    ('MY', 'Malásia', 'ms-MY', 'medium_value', 50, '🇲🇾', true, 'MYS', 'Malaysia', 'Malaysia', 'ms', 'ms', NULL, 2458, 'MYR', '["malasia", "malaysia", "my", "mys"]'::jsonb, true),
    ('MV', 'Maldivas', 'dv-MV', 'medium_value', 50, '🇲🇻', true, 'MDV', 'Maldives', 'Maldives', 'dv', 'dv', NULL, NULL, 'MVR', '["maldivas", "maldives", "mdv", "mv"]'::jsonb, true),
    ('ML', 'Mali', 'fr-ML', 'volume_play', 20, '🇲🇱', true, 'MLI', 'Mali', 'Mali', 'fr', 'fr', 1002, NULL, 'XOF', '["mali", "ml", "mli"]'::jsonb, true),
    ('MT', 'Malta', 'mt-MT', 'medium_value', 50, '🇲🇹', true, 'MLT', 'Malta', 'Malta', 'mt', 'mt', NULL, NULL, 'EUR', '["malta", "mlt", "mt"]'::jsonb, true),
    ('MH', 'Ilhas Marshall', 'en-MH', 'volume_play', 20, '🇲🇭', true, 'MHL', 'Marshall Islands', 'Marshall Islands', 'en', 'en', 1000, NULL, 'USD', '["ilhas marshall", "marshall islands", "mh", "mhl"]'::jsonb, true),
    ('MR', 'Mauritânia', 'ar-MR', 'volume_play', 20, '🇲🇷', true, 'MRT', 'Mauritania', 'موريتانيا', 'ar', 'ar', 1019, NULL, 'MRU', '["mauritania", "mr", "mrt", "موريتانيا"]'::jsonb, true),
    ('MU', 'Maurício', 'en-MU', 'medium_value', 50, '🇲🇺', true, 'MUS', 'Mauritius', 'Mauritius', 'en', 'en', 1000, NULL, 'MUR', '["mauricio", "mauritius", "mu", "mus"]'::jsonb, true),
    ('MX', 'México', 'es-MX', 'medium_value', 50, '🇲🇽', true, 'MEX', 'Mexico', 'México', 'es', 'es', 1003, 2484, 'MXN', '["mex", "mexico", "mx"]'::jsonb, true),
    ('FM', 'Micronésia', 'en-FM', 'volume_play', 20, '🇫🇲', true, 'FSM', 'Micronesia', 'Micronesia', 'en', 'en', 1000, NULL, 'USD', '["fm", "fsm", "micronesia"]'::jsonb, true),
    ('MD', 'Moldávia', 'ro-MD', 'volume_play', 20, '🇲🇩', true, 'MDA', 'Moldova', 'Moldova', 'ro', 'ro', 1032, NULL, 'MDL', '["md", "mda", "moldavia", "moldova"]'::jsonb, true),
    ('MC', 'Mônaco', 'fr-MC', 'high_value', 90, '🇲🇨', true, 'MCO', 'Monaco', 'Monaco', 'fr', 'fr', 1002, NULL, 'EUR', '["mc", "mco", "monaco"]'::jsonb, true),
    ('MN', 'Mongólia', 'mn-MN', 'volume_play', 20, '🇲🇳', true, 'MNG', 'Mongolia', 'Монгол', 'mn', 'mn', NULL, NULL, 'MNT', '["mn", "mng", "mongolia", "монгол"]'::jsonb, true),
    ('ME', 'Montenegro', 'sr-ME', 'volume_play', 20, '🇲🇪', true, 'MNE', 'Montenegro', 'Crna Gora', 'sr', 'sr', 1035, NULL, 'EUR', '["crna gora", "me", "mne", "montenegro"]'::jsonb, true),
    ('MA', 'Marrocos', 'ar-MA', 'volume_play', 20, '🇲🇦', true, 'MAR', 'Morocco', 'المغرب', 'ar', 'ar', 1019, NULL, 'MAD', '["ma", "mar", "marrocos", "morocco", "المغرب"]'::jsonb, true),
    ('MZ', 'Moçambique', 'pt-MZ', 'volume_play', 20, '🇲🇿', true, 'MOZ', 'Mozambique', 'Moçambique', 'pt', 'pt', 1014, NULL, 'MZN', '["mocambique", "moz", "mozambique", "mz"]'::jsonb, true),
    ('MM', 'Mianmar', 'my-MM', 'volume_play', 20, '🇲🇲', true, 'MMR', 'Myanmar', 'မြန်မာ', 'my', 'my', NULL, NULL, 'MMK', '["burma", "mianmar", "mm", "mmr", "myanmar", "မြနမာ"]'::jsonb, true),
    ('NA', 'Namíbia', 'en-NA', 'volume_play', 20, '🇳🇦', true, 'NAM', 'Namibia', 'Namibia', 'en', 'en', 1000, NULL, 'NAD', '["na", "nam", "namibia"]'::jsonb, true),
    ('NR', 'Nauru', 'en-NR', 'volume_play', 20, '🇳🇷', true, 'NRU', 'Nauru', 'Nauru', 'en', 'en', 1000, NULL, 'AUD', '["nauru", "nr", "nru"]'::jsonb, true),
    ('NP', 'Nepal', 'ne-NP', 'volume_play', 20, '🇳🇵', true, 'NPL', 'Nepal', 'नेपाल', 'ne', 'ne', NULL, NULL, 'NPR', '["nepal", "np", "npl", "नपाल"]'::jsonb, true),
    ('NL', 'Países Baixos', 'nl-NL', 'high_value', 90, '🇳🇱', true, 'NLD', 'Netherlands', 'Nederland', 'nl', 'nl', 1010, 2528, 'EUR', '["holanda", "nederland", "netherlands", "nl", "nld", "paises baixos"]'::jsonb, true),
    ('NZ', 'Nova Zelândia', 'en-NZ', 'high_value', 90, '🇳🇿', true, 'NZL', 'New Zealand', 'New Zealand', 'en', 'en', 1000, 2554, 'NZD', '["new zealand", "nova zelandia", "nz", "nzl"]'::jsonb, true),
    ('NI', 'Nicarágua', 'es-NI', 'volume_play', 20, '🇳🇮', true, 'NIC', 'Nicaragua', 'Nicaragua', 'es', 'es', 1003, NULL, 'NIO', '["ni", "nic", "nicaragua"]'::jsonb, true),
    ('NE', 'Níger', 'fr-NE', 'volume_play', 20, '🇳🇪', true, 'NER', 'Niger', 'Niger', 'fr', 'fr', 1002, NULL, 'XOF', '["ne", "ner", "niger"]'::jsonb, true),
    ('NG', 'Nigéria', 'en-NG', 'volume_play', 20, '🇳🇬', true, 'NGA', 'Nigeria', 'Nigeria', 'en', 'en', 1000, 2566, 'NGN', '["ng", "nga", "nigeria"]'::jsonb, true),
    ('KP', 'Coreia do Norte', 'ko-KP', 'volume_play', 20, '🇰🇵', true, 'PRK', 'North Korea', '조선민주주의인민공화국', 'ko', 'ko', 1012, NULL, 'KPW', '["coreia do norte", "kp", "north korea", "prk", "조선민주주의인민공화국"]'::jsonb, true),
    ('MK', 'Macedônia do Norte', 'mk-MK', 'volume_play', 20, '🇲🇰', true, 'MKD', 'North Macedonia', 'Северна Македонија', 'mk', 'mk', NULL, NULL, 'MKD', '["macedonia", "macedonia do norte", "mk", "mkd", "north macedonia", "северна македонија"]'::jsonb, true),
    ('NO', 'Noruega', 'nb-NO', 'high_value', 90, '🇳🇴', true, 'NOR', 'Norway', 'Norge', 'nb', 'nb', 1013, 2578, 'NOK', '["no", "nor", "norge", "noruega", "norway"]'::jsonb, true),
    ('OM', 'Omã', 'ar-OM', 'medium_value', 50, '🇴🇲', true, 'OMN', 'Oman', 'عُمان', 'ar', 'ar', 1019, NULL, 'OMR', '["om", "oma", "oman", "omn", "عمان"]'::jsonb, true),
    ('PK', 'Paquistão', 'ur-PK', 'volume_play', 20, '🇵🇰', true, 'PAK', 'Pakistan', 'پاکستان', 'ur', 'ur', NULL, NULL, 'PKR', '["pak", "pakistan", "paquistao", "pk", "پاکستان"]'::jsonb, true),
    ('PW', 'Palau', 'en-PW', 'volume_play', 20, '🇵🇼', true, 'PLW', 'Palau', 'Palau', 'en', 'en', 1000, NULL, 'USD', '["palau", "plw", "pw"]'::jsonb, true),
    ('PA', 'Panamá', 'es-PA', 'medium_value', 50, '🇵🇦', true, 'PAN', 'Panama', 'Panamá', 'es', 'es', 1003, NULL, 'PAB', '["pa", "pan", "panama"]'::jsonb, true),
    ('PG', 'Papua-Nova Guiné', 'en-PG', 'volume_play', 20, '🇵🇬', true, 'PNG', 'Papua New Guinea', 'Papua New Guinea', 'en', 'en', 1000, NULL, 'PGK', '["papua new guinea", "papua-nova guine", "pg", "png"]'::jsonb, true),
    ('PY', 'Paraguai', 'es-PY', 'volume_play', 20, '🇵🇾', true, 'PRY', 'Paraguay', 'Paraguay', 'es', 'es', 1003, 2600, 'PYG', '["paraguai", "paraguay", "pry", "py"]'::jsonb, true),
    ('PE', 'Peru', 'es-PE', 'volume_play', 20, '🇵🇪', true, 'PER', 'Peru', 'Perú', 'es', 'es', 1003, 2604, 'PEN', '["pe", "per", "peru"]'::jsonb, true),
    ('PH', 'Filipinas', 'fil-PH', 'volume_play', 20, '🇵🇭', true, 'PHL', 'Philippines', 'Pilipinas', 'fil', 'fil', NULL, 2608, 'PHP', '["filipinas", "ph", "philippines", "phl", "pilipinas"]'::jsonb, true),
    ('PL', 'Polônia', 'pl-PL', 'medium_value', 50, '🇵🇱', true, 'POL', 'Poland', 'Polska', 'pl', 'pl', 1030, 2616, 'PLN', '["pl", "pol", "poland", "polonia", "polska"]'::jsonb, true),
    ('PT', 'Portugal', 'pt-PT', 'medium_value', 50, '🇵🇹', true, 'PRT', 'Portugal', 'Portugal', 'pt', 'pt', 1014, 2620, 'EUR', '["portugal", "prt", "pt"]'::jsonb, true),
    ('QA', 'Catar', 'ar-QA', 'medium_value', 50, '🇶🇦', true, 'QAT', 'Qatar', 'قطر', 'ar', 'ar', 1019, NULL, 'QAR', '["catar", "qa", "qat", "qatar", "قطر"]'::jsonb, true),
    ('RO', 'Romênia', 'ro-RO', 'medium_value', 50, '🇷🇴', true, 'ROU', 'Romania', 'România', 'ro', 'ro', 1032, 2642, 'RON', '["ro", "romania", "romenia", "rou"]'::jsonb, true),
    ('RU', 'Rússia', 'ru-RU', 'medium_value', 50, '🇷🇺', true, 'RUS', 'Russia', 'Россия', 'ru', 'ru', 1031, 2643, 'RUB', '["ru", "rus", "russia", "россия"]'::jsonb, true),
    ('RW', 'Ruanda', 'rw-RW', 'volume_play', 20, '🇷🇼', true, 'RWA', 'Rwanda', 'Rwanda', 'rw', 'rw', NULL, NULL, 'RWF', '["ruanda", "rw", "rwa", "rwanda"]'::jsonb, true),
    ('KN', 'São Cristóvão e Névis', 'en-KN', 'volume_play', 20, '🇰🇳', true, 'KNA', 'Saint Kitts and Nevis', 'Saint Kitts and Nevis', 'en', 'en', 1000, NULL, 'XCD', '["kn", "kna", "saint kitts and nevis", "sao cristovao e nevis"]'::jsonb, true),
    ('LC', 'Santa Lúcia', 'en-LC', 'volume_play', 20, '🇱🇨', true, 'LCA', 'Saint Lucia', 'Saint Lucia', 'en', 'en', 1000, NULL, 'XCD', '["lc", "lca", "saint lucia", "santa lucia"]'::jsonb, true),
    ('VC', 'São Vicente e Granadinas', 'en-VC', 'volume_play', 20, '🇻🇨', true, 'VCT', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'en', 'en', 1000, NULL, 'XCD', '["saint vincent and the grenadines", "sao vicente e granadinas", "vc", "vct"]'::jsonb, true),
    ('WS', 'Samoa', 'sm-WS', 'volume_play', 20, '🇼🇸', true, 'WSM', 'Samoa', 'Samoa', 'sm', 'sm', NULL, NULL, 'WST', '["samoa", "ws", "wsm"]'::jsonb, true),
    ('SM', 'San Marino', 'it-SM', 'medium_value', 50, '🇸🇲', true, 'SMR', 'San Marino', 'San Marino', 'it', 'it', 1004, NULL, 'EUR', '["san marino", "sm", "smr"]'::jsonb, true),
    ('ST', 'São Tomé e Príncipe', 'pt-ST', 'volume_play', 20, '🇸🇹', true, 'STP', 'São Tomé and Príncipe', 'São Tomé e Príncipe', 'pt', 'pt', 1014, NULL, 'STN', '["sao tome", "sao tome and principe", "sao tome e principe", "st", "stp"]'::jsonb, true),
    ('SA', 'Arábia Saudita', 'ar-SA', 'medium_value', 50, '🇸🇦', true, 'SAU', 'Saudi Arabia', 'السعودية', 'ar', 'ar', 1019, 2682, 'SAR', '["arabia saudita", "sa", "sau", "saudi arabia", "السعودية"]'::jsonb, true),
    ('SN', 'Senegal', 'fr-SN', 'volume_play', 20, '🇸🇳', true, 'SEN', 'Senegal', 'Sénégal', 'fr', 'fr', 1002, NULL, 'XOF', '["sen", "senegal", "sn"]'::jsonb, true),
    ('RS', 'Sérvia', 'sr-RS', 'volume_play', 20, '🇷🇸', true, 'SRB', 'Serbia', 'Србија', 'sr', 'sr', 1035, NULL, 'RSD', '["rs", "serbia", "servia", "srb", "србија"]'::jsonb, true),
    ('SC', 'Seicheles', 'fr-SC', 'medium_value', 50, '🇸🇨', true, 'SYC', 'Seychelles', 'Seychelles', 'fr', 'fr', 1002, NULL, 'SCR', '["sc", "seicheles", "seychelles", "syc"]'::jsonb, true),
    ('SL', 'Serra Leoa', 'en-SL', 'volume_play', 20, '🇸🇱', true, 'SLE', 'Sierra Leone', 'Sierra Leone', 'en', 'en', 1000, NULL, 'SLE', '["serra leoa", "sierra leone", "sl", "sle"]'::jsonb, true),
    ('SG', 'Singapura', 'en-SG', 'high_value', 90, '🇸🇬', true, 'SGP', 'Singapore', 'Singapore', 'en', 'en', 1000, 2702, 'SGD', '["sg", "sgp", "singapore", "singapura"]'::jsonb, true),
    ('SK', 'Eslováquia', 'sk-SK', 'medium_value', 50, '🇸🇰', true, 'SVK', 'Slovakia', 'Slovensko', 'sk', 'sk', 1033, NULL, 'EUR', '["eslovaquia", "sk", "slovakia", "slovensko", "svk"]'::jsonb, true),
    ('SI', 'Eslovênia', 'sl-SI', 'medium_value', 50, '🇸🇮', true, 'SVN', 'Slovenia', 'Slovenija', 'sl', 'sl', NULL, NULL, 'EUR', '["eslovenia", "si", "slovenia", "slovenija", "svn"]'::jsonb, true),
    ('SB', 'Ilhas Salomão', 'en-SB', 'volume_play', 20, '🇸🇧', true, 'SLB', 'Solomon Islands', 'Solomon Islands', 'en', 'en', 1000, NULL, 'SBD', '["ilhas salomao", "sb", "slb", "solomon islands"]'::jsonb, true),
    ('SO', 'Somália', 'so-SO', 'volume_play', 20, '🇸🇴', true, 'SOM', 'Somalia', 'Soomaaliya', 'so', 'so', NULL, NULL, 'SOS', '["so", "som", "somalia", "soomaaliya"]'::jsonb, true),
    ('ZA', 'África do Sul', 'en-ZA', 'medium_value', 50, '🇿🇦', true, 'ZAF', 'South Africa', 'South Africa', 'en', 'en', 1000, 2710, 'ZAR', '["africa do sul", "south africa", "za", "zaf"]'::jsonb, true),
    ('KR', 'Coreia do Sul', 'ko-KR', 'high_value', 90, '🇰🇷', true, 'KOR', 'South Korea', '대한민국', 'ko', 'ko', 1012, 2410, 'KRW', '["coreia", "coreia do sul", "kor", "kr", "south korea", "대한민국"]'::jsonb, true),
    ('SS', 'Sudão do Sul', 'en-SS', 'volume_play', 20, '🇸🇸', true, 'SSD', 'South Sudan', 'South Sudan', 'en', 'en', 1000, NULL, 'SSP', '["south sudan", "ss", "ssd", "sudao do sul"]'::jsonb, true),
    ('ES', 'Espanha', 'es-ES', 'medium_value', 50, '🇪🇸', true, 'ESP', 'Spain', 'España', 'es', 'es', 1003, 2724, 'EUR', '["es", "esp", "espana", "espanha", "spain"]'::jsonb, true),
    ('LK', 'Sri Lanka', 'si-LK', 'volume_play', 20, '🇱🇰', true, 'LKA', 'Sri Lanka', 'ශ්‍රී ලංකා', 'si', 'si', NULL, NULL, 'LKR', '["lk", "lka", "sri lanka", "ශ‍ර ලංකා"]'::jsonb, true),
    ('SD', 'Sudão', 'ar-SD', 'volume_play', 20, '🇸🇩', true, 'SDN', 'Sudan', 'السودان', 'ar', 'ar', 1019, NULL, 'SDG', '["sd", "sdn", "sudan", "sudao", "السودان"]'::jsonb, true),
    ('SR', 'Suriname', 'nl-SR', 'volume_play', 20, '🇸🇷', true, 'SUR', 'Suriname', 'Suriname', 'nl', 'nl', 1010, NULL, 'SRD', '["sr", "sur", "suriname"]'::jsonb, true),
    ('SE', 'Suécia', 'sv-SE', 'high_value', 90, '🇸🇪', true, 'SWE', 'Sweden', 'Sverige', 'sv', 'sv', 1015, 2752, 'SEK', '["se", "suecia", "sverige", "swe", "sweden"]'::jsonb, true),
    ('CH', 'Suíça', 'de-CH', 'high_value', 90, '🇨🇭', true, 'CHE', 'Switzerland', 'Schweiz', 'de', 'de', 1001, 2756, 'CHF', '["ch", "che", "schweiz", "suica", "switzerland"]'::jsonb, true),
    ('SY', 'Síria', 'ar-SY', 'volume_play', 20, '🇸🇾', true, 'SYR', 'Syria', 'سوريا', 'ar', 'ar', 1019, NULL, 'SYP', '["siria", "sy", "syr", "syria", "سوريا"]'::jsonb, true),
    ('TJ', 'Tajiquistão', 'tg-TJ', 'volume_play', 20, '🇹🇯', true, 'TJK', 'Tajikistan', 'Тоҷикистон', 'tg', 'tg', NULL, NULL, 'TJS', '["tajikistan", "tajiquistao", "tj", "tjk", "тоҷикистон"]'::jsonb, true),
    ('TZ', 'Tanzânia', 'sw-TZ', 'volume_play', 20, '🇹🇿', true, 'TZA', 'Tanzania', 'Tanzania', 'sw', 'sw', NULL, NULL, 'TZS', '["tanzania", "tz", "tza"]'::jsonb, true),
    ('TH', 'Tailândia', 'th-TH', 'medium_value', 50, '🇹🇭', true, 'THA', 'Thailand', 'ประเทศไทย', 'th', 'th', 1044, 2764, 'THB', '["tailandia", "th", "tha", "thailand", "ประเทศไทย"]'::jsonb, true),
    ('TL', 'Timor-Leste', 'pt-TL', 'volume_play', 20, '🇹🇱', true, 'TLS', 'Timor-Leste', 'Timor-Leste', 'pt', 'pt', 1014, NULL, 'USD', '["east timor", "timor leste", "timor-leste", "tl", "tls"]'::jsonb, true),
    ('TG', 'Togo', 'fr-TG', 'volume_play', 20, '🇹🇬', true, 'TGO', 'Togo', 'Togo', 'fr', 'fr', 1002, NULL, 'XOF', '["tg", "tgo", "togo"]'::jsonb, true),
    ('TO', 'Tonga', 'en-TO', 'volume_play', 20, '🇹🇴', true, 'TON', 'Tonga', 'Tonga', 'en', 'en', 1000, NULL, 'TOP', '["to", "ton", "tonga"]'::jsonb, true),
    ('TT', 'Trindade e Tobago', 'en-TT', 'medium_value', 50, '🇹🇹', true, 'TTO', 'Trinidad and Tobago', 'Trinidad and Tobago', 'en', 'en', 1000, NULL, 'TTD', '["trindade e tobago", "trinidad", "trinidad and tobago", "tt", "tto"]'::jsonb, true),
    ('TN', 'Tunísia', 'ar-TN', 'volume_play', 20, '🇹🇳', true, 'TUN', 'Tunisia', 'تونس', 'ar', 'ar', 1019, NULL, 'TND', '["tn", "tun", "tunisia", "تونس"]'::jsonb, true),
    ('TR', 'Turquia', 'tr-TR', 'medium_value', 50, '🇹🇷', true, 'TUR', 'Turkey', 'Türkiye', 'tr', 'tr', 1037, 2792, 'TRY', '["tr", "tur", "turkey", "turkiye", "turquia"]'::jsonb, true),
    ('TM', 'Turcomenistão', 'tk-TM', 'volume_play', 20, '🇹🇲', true, 'TKM', 'Turkmenistan', 'Türkmenistan', 'tk', 'tk', NULL, NULL, 'TMT', '["tkm", "tm", "turcomenistao", "turkmenistan"]'::jsonb, true),
    ('TV', 'Tuvalu', 'en-TV', 'volume_play', 20, '🇹🇻', true, 'TUV', 'Tuvalu', 'Tuvalu', 'en', 'en', 1000, NULL, 'AUD', '["tuv", "tuvalu", "tv"]'::jsonb, true),
    ('UG', 'Uganda', 'en-UG', 'volume_play', 20, '🇺🇬', true, 'UGA', 'Uganda', 'Uganda', 'en', 'en', 1000, NULL, 'UGX', '["ug", "uga", "uganda"]'::jsonb, true),
    ('UA', 'Ucrânia', 'uk-UA', 'medium_value', 50, '🇺🇦', true, 'UKR', 'Ukraine', 'Україна', 'uk', 'uk', 1036, 2804, 'UAH', '["ua", "ucrania", "ukr", "ukraine", "украіна"]'::jsonb, true),
    ('AE', 'Emirados Árabes Unidos', 'ar-AE', 'high_value', 90, '🇦🇪', true, 'ARE', 'United Arab Emirates', 'الإمارات العربية المتحدة', 'ar', 'ar', 1019, 2784, 'AED', '["ae", "are", "emirados", "emirados arabes unidos", "uae", "united arab emirates", "الامارات العربية المتحدة"]'::jsonb, true),
    ('GB', 'Reino Unido', 'en-GB', 'high_value', 90, '🇬🇧', true, 'GBR', 'United Kingdom', 'United Kingdom', 'en', 'en', 1000, 2826, 'GBP', '["england", "gb", "gbr", "gra bretanha", "great britain", "inglaterra", "reino unido", "uk", "united kingdom"]'::jsonb, true),
    ('US', 'Estados Unidos', 'en-US', 'high_value', 90, '🇺🇸', true, 'USA', 'United States', 'United States', 'en', 'en', 1000, 2840, 'USD', '["america", "estados unidos", "estados unidos da america", "eua", "united states", "united states of america", "us", "usa"]'::jsonb, true),
    ('UY', 'Uruguai', 'es-UY', 'medium_value', 50, '🇺🇾', true, 'URY', 'Uruguay', 'Uruguay', 'es', 'es', 1003, 2858, 'UYU', '["uruguai", "uruguay", "ury", "uy"]'::jsonb, true),
    ('UZ', 'Uzbequistão', 'uz-UZ', 'volume_play', 20, '🇺🇿', true, 'UZB', 'Uzbekistan', 'Oʻzbekiston', 'uz', 'uz', NULL, NULL, 'UZS', '["oʻzbekiston", "uz", "uzb", "uzbekistan", "uzbequistao"]'::jsonb, true),
    ('VU', 'Vanuatu', 'bi-VU', 'volume_play', 20, '🇻🇺', true, 'VUT', 'Vanuatu', 'Vanuatu', 'bi', 'bi', NULL, NULL, 'VUV', '["vanuatu", "vu", "vut"]'::jsonb, true),
    ('VA', 'Vaticano', 'it-VA', 'medium_value', 50, '🇻🇦', true, 'VAT', 'Vatican City', 'Città del Vaticano', 'it', 'it', 1004, NULL, 'EUR', '["citta del vaticano", "holy see", "santa se", "va", "vat", "vatican", "vatican city", "vaticano"]'::jsonb, true),
    ('VE', 'Venezuela', 'es-VE', 'volume_play', 20, '🇻🇪', true, 'VEN', 'Venezuela', 'Venezuela', 'es', 'es', 1003, 2862, 'VES', '["ve", "ven", "venezuela"]'::jsonb, true),
    ('VN', 'Vietnã', 'vi-VN', 'volume_play', 20, '🇻🇳', true, 'VNM', 'Vietnam', 'Việt Nam', 'vi', 'vi', 1040, 2704, 'VND', '["viet nam", "vietna", "vietnam", "vn", "vnm"]'::jsonb, true),
    ('YE', 'Iêmen', 'ar-YE', 'volume_play', 20, '🇾🇪', true, 'YEM', 'Yemen', 'اليمن', 'ar', 'ar', 1019, NULL, 'YER', '["iemen", "ye", "yem", "yemen", "اليمن"]'::jsonb, true),
    ('ZM', 'Zâmbia', 'en-ZM', 'volume_play', 20, '🇿🇲', true, 'ZMB', 'Zambia', 'Zambia', 'en', 'en', 1000, NULL, 'ZMW', '["zambia", "zm", "zmb"]'::jsonb, true),
    ('ZW', 'Zimbábue', 'en-ZW', 'volume_play', 20, '🇿🇼', true, 'ZWE', 'Zimbabwe', 'Zimbabwe', 'en', 'en', 1000, NULL, 'ZWL', '["zimbabue", "zimbabwe", "zw", "zwe"]'::jsonb, true),
    ('PS', 'Palestina', 'ar-PS', 'volume_play', 20, '🇵🇸', true, 'PSE', 'Palestine', 'فلسطين', 'ar', 'ar', 1019, NULL, 'ILS', '["palestina", "palestine", "ps", "pse", "state of palestine", "فلسطين"]'::jsonb, true)
ON CONFLICT (country_code) DO UPDATE SET
    country_name          = EXCLUDED.country_name,
    native_language       = EXCLUDED.native_language,
    market_tier           = EXCLUDED.market_tier,
    flag_emoji            = EXCLUDED.flag_emoji,
    is_active             = true,
    iso3                  = EXCLUDED.iso3,
    name_en               = EXCLUDED.name_en,
    name_native           = EXCLUDED.name_native,
    language_code         = EXCLUDED.language_code,
    language_short        = EXCLUDED.language_short,
    language_constant     = EXCLUDED.language_constant,
    google_ads_geo_target = EXCLUDED.google_ads_geo_target,
    currency_code         = EXCLUDED.currency_code,
    aliases               = EXCLUDED.aliases,
    is_sovereign          = true,
    updated_at            = now();

-- =====================================================================
-- Verificação (opcional) — deve retornar 195:
-- SELECT count(*) FROM public.pautador_countries WHERE is_active = true AND is_sovereign = true;
-- SELECT country_code, country_name, market_tier FROM public.pautador_countries ORDER BY country_name;
-- =====================================================================
