from __future__ import annotations

import json

from pydantic import Field, field_validator
from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    openai_api_key: str = ""
    gemini_api_key: str = ""
    openai_model: str = "gpt-4o"  # fallback blueprint model if blueprint_model is empty
    # Blueprint (text) model for ALL content types. A "gemini-*" value routes blueprint
    # generation to the Gemini OpenAI-compatible endpoint (uses GEMINI_API_KEY); anything
    # else uses OpenAI (OPENAI_API_KEY). Optional per-type override below.
    blueprint_model: str = "gemini-3.5-flash"
    # Optional per-type overrides (empty = use blueprint_model). e.g. keep news on gpt-4o.
    blueprint_model_meta_ads: str = ""
    blueprint_model_news: str = ""
    blueprint_model_pinterest: str = ""
    # Max output tokens for blueprint generation — generous headroom because "thinking"
    # models (e.g. gemini-3.5-flash) spend many internal tokens before the visible text.
    blueprint_max_tokens: int = 8000
    # Web-search-capable model for the research step (Responses API hosted web_search).
    # gpt-4o does NOT support hosted web_search — use gpt-4.1 / gpt-4.1-mini / GPT-5 family.
    strategist_model: str = "gpt-4.1"
    enable_web_search: bool = True
    gemini_model: str = "gemini-3.1-flash-image-preview"
    openai_image_model: str = "gpt-image-2"
    # Native generation cap: longest edge generated by the image model before local
    # Pillow upscaling to the exact target. 1536 = cheapest tier; bump to 2048 for
    # sharper 4K at higher cost. Both edges are snapped to multiples of 16.
    image_native_max_edge: int = 1536
    image_quality: str = "medium"  # low | medium | high — affects cost ~15x (low→high)
    image_generation_delay_seconds: float = 3.0
    # Rolling parallelism for image generation (semaphore size). Default 3 is a safe
    # middle ground for OpenAI image rate limits; configurable via IMAGE_CONCURRENCY.
    image_concurrency: int = 3
    port: int = 8001
    # Stored as str; accepts both JSON array and comma-separated in .env
    cors_origins: str = "http://localhost:8089,http://localhost:3000"
    image_provider: str = "gemini"  # "gemini" | "openai-image" | "mock"

    def get_cors_list(self) -> list[str]:
        v = self.cors_origins.strip()
        if v.startswith("["):
            return json.loads(v)
        return [o.strip() for o in v.split(",") if o.strip()]

    def blueprint_model_for(self, content_type: str) -> str:
        """Which text model generates the blueprint for this content type.

        Per-type override → global blueprint_model → openai_model (last-resort).
        """
        overrides = {
            "meta-ads": self.blueprint_model_meta_ads,
            "news": self.blueprint_model_news,
            "pinterest": self.blueprint_model_pinterest,
        }
        return (
            overrides.get(content_type, "").strip()
            or self.blueprint_model.strip()
            or self.openai_model
        )

    model_config = {"env_file": ".env", "env_file_encoding": "utf-8"}


settings = Settings()
