-- ============================================================================
-- Join Ads — eixo de campanha
--
-- Espelha a `gam_metrics` para a fonte Join Ads e converge no MESMO ponto que
-- o dashboard já lê: `daily_campaign_metrics`.
--
-- Por que tabela nova em vez de uma coluna `source` na gam_metrics: a
-- gam_metrics tem 8 triggers pendurados e é o único caminho de receita do
-- dashboard. Generalizar ela é risco alto por ganho zero — a unificação já
-- existe e é a daily_campaign_metrics.
--
-- Aplicar com:
--   cat src/sql/joinads/01_joinads_metrics.sql | ssh -i ~/.ssh/volc_hetzner_claude_ed25519 \
--     root@178.156.196.149 "docker exec -i supabase-db psql -U postgres -v ON_ERROR_STOP=1"
-- ============================================================================

BEGIN;

-- ─── tabela ─────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.joinads_metrics (
    id                   integer   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date                 date      NOT NULL,
    utm_campaign_value   varchar   NOT NULL,
    joinads_domain       varchar   NOT NULL,
    project_id           integer   REFERENCES public.projects(id),

    -- SEMPRE bruto. Quem desconta o revshare da Join é o consumidor final,
    -- via projects.revshare — igual ao que já acontece com GAM/AdSense.
    revenue              numeric   NOT NULL DEFAULT 0,
    revenue_converted    numeric   DEFAULT 0,

    impressions          bigint    DEFAULT 0,
    clicks               bigint    DEFAULT 0,
    ctr                  numeric   DEFAULT 0,   -- percentual (2.5 = 2,5%)
    ecpm                 numeric   DEFAULT 0,
    viewable_impressions numeric   DEFAULT 0,   -- percentual de viewability

    created_at           timestamp DEFAULT now(),
    updated_at           timestamp DEFAULT now()
);

-- É esta unique que o PostgREST usa no `?on_conflict=` do upsert do n8n.
CREATE UNIQUE INDEX IF NOT EXISTS joinads_metrics_unique
    ON public.joinads_metrics (date, utm_campaign_value, joinads_domain);

CREATE INDEX IF NOT EXISTS idx_joinads_metrics_date
    ON public.joinads_metrics (date);
CREATE INDEX IF NOT EXISTS idx_joinads_metrics_project
    ON public.joinads_metrics (project_id);

-- RLS fica desligada, igual gam_metrics / adsense_metrics / daily_campaign_metrics.

-- ─── resolve o project_id pelo domínio ──────────────────────────────────────

CREATE OR REPLACE FUNCTION public.auto_populate_project_id_joinads()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
    dominio text;
BEGIN
    IF NEW.project_id IS NULL THEN
        dominio := lower(trim(regexp_replace(
                     regexp_replace(NEW.joinads_domain, '^https?://', '', 'i'),
                     '^www\.', '', 'i')));

        SELECT p.id INTO NEW.project_id
        FROM public.projects p
        WHERE lower(trim(regexp_replace(
                  regexp_replace(coalesce(p.domain, p.main_url, ''), '^https?://', '', 'i'),
                  '^www\.', '', 'i'))) = dominio
        LIMIT 1;
    END IF;

    NEW.updated_at := now();
    RETURN NEW;
END;
$function$;

-- ─── fan-out para daily_campaign_metrics ────────────────────────────────────
--
-- As métricas da Join caem nas colunas `gam_*` porque é de lá que o front lê —
-- elas são o slot genérico de "lado da monetização", não exclusivas do GAM.
-- gam_cpc / match_rate / unfilled_impressions ficam de fora: a Join não entrega
-- essas três a nível de campanha (só de domínio), e escrever 0 apagaria valor
-- vindo de outra fonte.

CREATE OR REPLACE FUNCTION public.sync_joinads_revenue_to_daily_metrics()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    UPDATE public.daily_campaign_metrics
    SET revenue              = NEW.revenue,
        gam_impressions      = NEW.impressions,
        gam_clicks           = NEW.clicks,
        gam_ctr              = NEW.ctr,
        gam_ecpm             = NEW.ecpm,
        viewable_impressions = NEW.viewable_impressions,
        updated_at           = now()
    WHERE campaign_id = NEW.utm_campaign_value
      AND date        = NEW.date;

    IF NOT FOUND THEN
        INSERT INTO public.daily_campaign_metrics (
            campaign_id, date, revenue,
            gam_impressions, gam_clicks, gam_ctr, gam_ecpm, viewable_impressions,
            spend, clicks, impressions, conversions, cpc, ctr, roas,
            cost_per_conversion, page_views, ecpm, viewability, pmr, rps
        ) VALUES (
            NEW.utm_campaign_value, NEW.date, NEW.revenue,
            NEW.impressions, NEW.clicks, NEW.ctr, NEW.ecpm, NEW.viewable_impressions,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0
        );
    END IF;

    RETURN NEW;
END;
$function$;

-- ─── triggers ───────────────────────────────────────────────────────────────
--
-- Ordem de disparo no Postgres é ALFABÉTICA pelo nome do trigger. Aqui isso não
-- morde: `trg_joinads_project_id` mexe só em project_id/updated_at e
-- `trg_joinads_revenue_converted` mexe só em revenue_converted.
--
-- De propósito existe UMA só função de conversão — a histórica por data. Na
-- gam_metrics duas funções disputam a mesma coluna e quem vence é a ordem do
-- nome, o que faz backfill de mês passado sair com o dólar de hoje. Não repito.

DROP TRIGGER IF EXISTS trg_joinads_project_id ON public.joinads_metrics;
CREATE TRIGGER trg_joinads_project_id
    BEFORE INSERT OR UPDATE ON public.joinads_metrics
    FOR EACH ROW EXECUTE FUNCTION public.auto_populate_project_id_joinads();

DROP TRIGGER IF EXISTS trg_joinads_revenue_converted ON public.joinads_metrics;
CREATE TRIGGER trg_joinads_revenue_converted
    BEFORE INSERT OR UPDATE ON public.joinads_metrics
    FOR EACH ROW EXECUTE FUNCTION public.calculate_revenue_converted_by_date();

DROP TRIGGER IF EXISTS trg_joinads_sync_daily ON public.joinads_metrics;
CREATE TRIGGER trg_joinads_sync_daily
    AFTER INSERT OR UPDATE ON public.joinads_metrics
    FOR EACH ROW EXECUTE FUNCTION public.sync_joinads_revenue_to_daily_metrics();

COMMIT;
