"""Pacote de observabilidade read-only para Performance Max (PMax) da Google Ads API v25."""

from volc_ads.observabilidade_pmax.coverage import (
    OBSERVABILITY_DISCLAIMER,
    PMAX_FIELD_REQUIREMENTS,
    AssetFieldCoverageStatus,
    AssetFieldRequirement,
    PMaxAssetGroupCoverageReport,
    PMaxCampaignCoverageReport,
    CoverageVerdict,
    evaluate_asset_field_coverage,
    evaluate_asset_group_coverage,
    evaluate_campaign_coverage,
)
from volc_ads.observabilidade_pmax.kernel import PMaxObservabilityKernel
from volc_ads.observabilidade_pmax.projector import (
    assemble_pmax_bundle,
    extract_nested_path,
    extract_observed,
    project_asset_group_asset_row,
    project_asset_group_row,
    project_asset_group_signal_row,
    project_campaign_asset_row,
    project_asset_row,
    project_campaign_metrics,
    project_campaign_row,
)
from volc_ads.observabilidade_pmax.queries import (
    GAQLSecurityError,
    assert_read_only_gaql,
    build_pmax_asset_group_assets_query,
    build_pmax_asset_group_signals_query,
    build_pmax_asset_groups_query,
    build_pmax_assets_query,
    build_pmax_campaigns_query,
    build_pmax_campaign_assets_query,
    build_pmax_observability_bundle_queries,
    validate_customer_id,
    validate_identifier,
    assert_v25_descriptor_contract,
    PMaxV25ContractError,
)
from volc_ads.observabilidade_pmax.types import (
    ObservationState,
    CollectionState,
    CollectionEnvelope,
    ObservedValue,
    PMaxAdStrength,
    PMaxAssetDTO,
    PMaxAssetFieldType,
    PMaxAssetGroupAssetDTO,
    PMaxAssetGroupDTO,
    PMaxAssetGroupPrimaryStatus,
    PMaxAssetGroupPrimaryStatusReason,
    PMaxAssetGroupSignalDTO,
    PMaxAssetGroupStatus,
    PMaxAssetPerformanceLabel,
    PMaxAssetPolicyApprovalStatus,
    PMaxBiddingStrategyType,
    PMaxCampaignDTO,
    PMaxCampaignAssetDTO,
    PMaxRawSnapshot,
    PMaxDiagnosisOutcome,
    PMaxCampaignMetricsDTO,
    PMaxCampaignServingStatus,
    PMaxCampaignStatus,
)

__all__ = [
    # Kernel
    "PMaxObservabilityKernel",
    # Types & Enums
    "ObservationState",
    "CollectionState",
    "CollectionEnvelope",
    "ObservedValue",
    "PMaxAssetFieldType",
    "PMaxAssetPerformanceLabel",
    "PMaxAdStrength",
    "PMaxAssetGroupStatus",
    "PMaxAssetGroupPrimaryStatus",
    "PMaxAssetGroupPrimaryStatusReason",
    "PMaxCampaignStatus",
    "PMaxCampaignServingStatus",
    "PMaxBiddingStrategyType",
    "PMaxAssetPolicyApprovalStatus",
    # DTOs
    "PMaxAssetDTO",
    "PMaxAssetGroupAssetDTO",
    "PMaxAssetGroupSignalDTO",
    "PMaxAssetGroupDTO",
    "PMaxCampaignMetricsDTO",
    "PMaxCampaignDTO",
    "PMaxCampaignAssetDTO",
    "PMaxRawSnapshot",
    "PMaxDiagnosisOutcome",
    # Queries
    "GAQLSecurityError",
    "assert_read_only_gaql",
    "validate_customer_id",
    "validate_identifier",
    "build_pmax_campaigns_query",
    "build_pmax_campaign_assets_query",
    "build_pmax_asset_groups_query",
    "build_pmax_asset_group_assets_query",
    "build_pmax_assets_query",
    "build_pmax_asset_group_signals_query",
    "build_pmax_observability_bundle_queries",
    "assert_v25_descriptor_contract",
    "PMaxV25ContractError",
    # Projector
    "extract_nested_path",
    "extract_observed",
    "project_asset_row",
    "project_asset_group_asset_row",
    "project_asset_group_signal_row",
    "project_campaign_asset_row",
    "project_asset_group_row",
    "project_campaign_metrics",
    "project_campaign_row",
    "assemble_pmax_bundle",
    # Coverage
    "OBSERVABILITY_DISCLAIMER",
    "PMAX_FIELD_REQUIREMENTS",
    "AssetFieldRequirement",
    "AssetFieldCoverageStatus",
    "PMaxAssetGroupCoverageReport",
    "PMaxCampaignCoverageReport",
    "CoverageVerdict",
    "evaluate_asset_field_coverage",
    "evaluate_asset_group_coverage",
    "evaluate_campaign_coverage",
]
